// gfx2d_fx_gen.h: GENERATED by tools/gfx_fx_gen.py from src/native/gfx2d/fx/*.fx. Do not edit: change the .fx and run the tool.
//
// Include it with the parts you want defined first: GFX_FX_WANT_INFO (the core: names and defaults), GFX_FX_WANT_SOFT (the CPU reference),
// GFX_FX_WANT_GLSL (the shaders of the GL backend).
#ifndef STRIDE2D_GFX2D_FX_GEN_H
#define STRIDE2D_GFX2D_FX_GEN_H

#include "gfx2d.h"

#if GFX_FX_PARAMS != 128
#error "GFX_FX_PARAMS in gfx2d.h is not PARAM_FLOATS of tools/gfx_fx_gen.py"
#endif

#if GFX_FX_ID_MAX != 16
#error "gfx2d.h and gfx2d_fx_gen.h are from different registries: run tools/gfx_fx_gen.py"
#endif

#ifdef GFX_FX_WANT_INFO
typedef struct GfxFxInfo
{
	const char* name; // NULL: no effect has this id
	int nparams;
	float defaults[GFX_FX_PARAMS];
} GfxFxInfo;
static const GfxFxInfo gfx_fx_info[GFX_FX_ID_MAX + 1] = {
	{ NULL, 0, { 0 } },
	{ "bright_contrast", 2, { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 1
	{ "tint", 5, { 1.0f, 0.5f, 0.1f, 1.0f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 2
	{ "blend", 9, { 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.5f, 0.1f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 3
	{ "hsv_adjust", 9, { 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 4
	{ "hls_adjust", 10, { 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 5
	{ "levels", 6, { 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 6
	{ "levels_rgb", 16, { 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 7
	{ "linear_gradient", 18, { 0.5f, 0.5f, 0.0f, 200.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 8
	{ "radial_gradient", 14, { 0.5f, 0.5f, 100.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 9
	{ "square_gradient", 13, { 0.5f, 0.5f, 200.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 10
	{ "diamond_gradient", 13, { 0.5f, 0.5f, 100.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 11
	{ "spin_gradient", 14, { 0.5f, 0.5f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 12
	{ "four_points_gradient", 25, { 0.9f, 0.1f, 0.1f, 0.1f, 0.1f, 0.9f, 0.9f, 0.9f, 1.0f, 0.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, 1.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0.0f, 1.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 13
	{ "lights", 32, { 0.18f, 0.2f, 0.3f, 1.0f, 1.0f, 0.15f, 0.3f, 0.5f, 0.35f, 1.0f, 0.0f, 0.0f, 1.0f, 0.8f, 0.5f, 1.0f, 0.7f, 0.4f, 0.3f, 0.0f, 0.4f, 0.7f, 1.0f, 1.0f, 0.5f, 0.8f, 0.25f, 0.0f, 1.0f, 0.4f, 0.6f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 14
	{ "spot_light", 17, { 0.12f, 0.13f, 0.2f, 1.0f, 0.5f, 0.1f, -90.0f, 30.0f, 0.4f, 1.0f, 1.2f, 1.0f, 1.0f, 0.95f, 0.8f, 1.0f, 0.1f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 15
	{ "scene_lights", 104, { 0.18f, 0.2f, 0.3f, 1.0f, 1.0f, 0.15f, 1.0f, 1.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.5f, 0.5f, 0.3f, 0.0f, 1.0f, 0.9f, 0.7f, 1.0f, -90.0f, 30.0f, 0.4f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f } }, // 16
};
#endif

#ifdef GFX_FX_WANT_SOFT
#include <math.h>
#include <stddef.h>

// the CPU reference: `c` is the pixel (r, g, b, a in 0..1), u and v its place over the picture (v from the TOP)

// bright_contrast.fx

static void gfx_fx_soft_bright_contrast( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float brightness = p[0];
	(void)brightness;
	float contrast = p[1];
	(void)contrast;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float k = contrast < 0.0f ? 1.0f + contrast : 1.0f + 3.0f * contrast;
	int i;
	for ( i = 0; i < 3; i++ )
		c[i] = ( c[i] - 0.5f ) * k + 0.5f + brightness;
}

// tint.fx

static void gfx_fx_soft_tint( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	const float* color = &p[0];
	(void)color;
	float amount = p[4];
	(void)amount;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	int i;
	for ( i = 0; i < 3; i++ )
		c[i] = c[i] * ( 1.0f - amount ) + c[i] * color[i] * amount;
}

// blend.fx
static float fxb_burn( float d, float u ) { return u <= 0.f ? 0.f : 1.f - fminf( 1.f, ( 1.f - d ) / u ); }
static float fxb_dodge( float d, float u ) { return u >= 1.f ? 1.f : fminf( 1.f, d / ( 1.f - u ) ); }
static float fxb_screen( float d, float u ) { return 1.f - ( 1.f - d ) * ( 1.f - u ); }
static float fxb_clamp( float x ) { return x < 0.f ? 0.f : x > 1.f ? 1.f : x; }
static float fxb_ch( int m, float d, float u )
{
	switch ( m )
	{
	case 0: return u;
	case 1: return d * u;
	case 2: return u <= 0.f ? 1.f : d / u;
	case 3: return fxb_burn( d, u );
	case 4: return fxb_clamp( d + u - 1.f );
	case 5: return fminf( d, u );
	case 7: return fmaxf( d, u );
	case 8: return fxb_screen( d, u );
	case 9: return fxb_dodge( d, u );
	case 10: return fminf( 1.f, d + u );
	case 12: return d < 0.5f ? u * ( 2.f * d ) : fxb_screen( u, 2.f * d - 1.f );
	case 13:
		if ( u < 0.5f )
			return d + ( d - d * d ) * ( 2.f * u - 1.f );
		if ( d < 0.25f )
			return d + ( 2.f * u - 1.f ) * ( ( ( 16.f * d - 12.f ) * d + 4.f ) * d - d );
		return d + ( 2.f * u - 1.f ) * ( sqrtf( d ) - d );
	case 14: return u < 0.5f ? d * ( 2.f * u ) : fxb_screen( d, 2.f * u - 1.f );
	case 15: return u < 0.5f ? fxb_burn( d, 2.f * u ) : fxb_dodge( d, 2.f * u - 1.f );
	case 16: return u < 0.5f ? fxb_clamp( d + 2.f * u - 1.f ) : fminf( 1.f, d + 2.f * u - 1.f );
	case 17: return u < 0.5f ? fminf( 2.f * u, d ) : fmaxf( 2.f * u - 1.f, d );
	}
	return ( u < 0.5f ? fxb_burn( d, 2.f * u ) : fxb_dodge( d, 2.f * u - 1.f ) ) < 0.5f ? 0.f : 1.f;
}
static void gfx_fx_soft_blend( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	int mode = (int)floorf( p[0] + 0.5f );
	(void)mode;
	const float* color = &p[4];
	(void)color;
	float opacity = p[8];
	(void)opacity;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float b[3];
	int i;
	if ( mode == 6 || mode == 11 )
	{
		float ld = 0.298912f * c[0] + 0.586611f * c[1] + 0.114478f * c[2];
		float lu = 0.298912f * color[0] + 0.586611f * color[1] + 0.114478f * color[2];
		int up_wins = mode == 6 ? !( ld < lu ) : ( ld < lu );
		for ( i = 0; i < 3; i++ )
			b[i] = up_wins ? color[i] : c[i];
	}
	else
		for ( i = 0; i < 3; i++ )
			b[i] = fxb_ch( mode, c[i], color[i] );
	for ( i = 0; i < 3; i++ )
		c[i] = c[i] + ( b[i] - c[i] ) * ( color[3] * opacity );
}

// hsv_adjust.fx
static void fxh_to_hsv( const float* c, float* o )
{
	float mx = fmaxf( c[0], fmaxf( c[1], c[2] ) ), mn = fminf( c[0], fminf( c[1], c[2] ) );
	float h = 0.f, s = 0.f, d = mx - mn;
	if ( mx != mn )
	{
		s = d / mx;
		if ( c[0] == mx )
			h = ( c[1] - c[2] ) / d;
		else if ( c[1] == mx )
			h = 2.f + ( c[2] - c[0] ) / d;
		else
			h = 4.f + ( c[0] - c[1] ) / d;
		h *= 60.f;
		if ( h < 0.f )
			h += 360.f;
	}
	o[0] = h; o[1] = s; o[2] = mx;
}
static void fxh_from_hsv( float h, float s, float v, float* o )
{
	float hh, i, f, p, q, t;
	int k;
	if ( s == 0.f )
	{
		o[0] = o[1] = o[2] = v;
		return;
	}
	hh = ( h - 360.f * floorf( h / 360.f ) ) / 60.f;
	if ( hh >= 6.f )
		hh -= 6.f;
	i = floorf( hh ); f = hh - i;
	p = v * ( 1.f - s ); q = v * ( 1.f - s * f ); t = v * ( 1.f - s * ( 1.f - f ) );
	k = (int)i;
	switch ( k )
	{
	case 0: o[0] = v; o[1] = t; o[2] = p; break;
	case 1: o[0] = q; o[1] = v; o[2] = p; break;
	case 2: o[0] = p; o[1] = v; o[2] = t; break;
	case 3: o[0] = p; o[1] = q; o[2] = v; break;
	case 4: o[0] = t; o[1] = p; o[2] = v; break;
	default: o[0] = v; o[1] = p; o[2] = q; break;
	}
}
static void gfx_fx_soft_hsv_adjust( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float huePivot = p[0];
	(void)huePivot;
	float hueScale = p[1];
	(void)hueScale;
	float hueShift = p[2];
	(void)hueShift;
	float valPivot = p[3];
	(void)valPivot;
	float valScale = p[4];
	(void)valScale;
	float valShift = p[5];
	(void)valShift;
	float satPivot = p[6];
	(void)satPivot;
	float satScale = p[7];
	(void)satScale;
	float satShift = p[8];
	(void)satShift;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float hsv[3], rgb[3];
	fxh_to_hsv( c, hsv );
	if ( hueScale != 1.f || hueShift != 0.f )
	{
		float d = hsv[0] - huePivot, h;
		d = d - 360.f * floorf( ( d + 180.f ) / 360.f );
		h = d * hueScale + huePivot + hueShift;
		hsv[0] = h - 360.f * floorf( h / 360.f );
	}
	if ( satScale != 1.f || satShift != 0.f )
	{
		hsv[1] = ( hsv[1] - satPivot ) * satScale + satPivot + satShift;
		if ( hsv[1] < 0.f )
			hsv[1] = 0.f;
	}
	if ( valScale != 1.f || valShift != 0.f )
		hsv[2] = ( hsv[2] - valPivot ) * valScale + valPivot + valShift;
	fxh_from_hsv( hsv[0], hsv[1], hsv[2], rgb );
	c[0] = rgb[0]; c[1] = rgb[1]; c[2] = rgb[2];
}

// hls_adjust.fx
static void fxl_to_hls( const float* c, int cyl, float* o )
{
	float mx = fmaxf( c[0], fmaxf( c[1], c[2] ) ), mn = fminf( c[0], fminf( c[1], c[2] ) );
	float h = 0.f, s = 0.f, l = ( mx + mn ) / 2.f;
	if ( mx != mn )
	{
		float d = mx - mn, rm, gm, bm;
		if ( cyl )
			s = l <= 0.5f ? d / ( mx + mn ) : d / ( 2.f - ( mx + mn ) );
		else
			s = d;
		rm = ( mx - c[0] ) / d; gm = ( mx - c[1] ) / d; bm = ( mx - c[2] ) / d;
		if ( c[0] == mx )
			h = bm - gm;
		else if ( c[1] == mx )
			h = 2.f + rm - bm;
		else
			h = 4.f + gm - rm;
		h *= 60.f;
		if ( h < 0.f )
			h += 360.f;
	}
	o[0] = h; o[1] = l; o[2] = s;
}
static float fxl_calc( float m1, float m2, float hue )
{
	float hh = hue - 360.f * floorf( hue / 360.f );
	if ( hh < 60.f )
		return m1 + ( m2 - m1 ) * hh / 60.f;
	if ( hh < 180.f )
		return m2;
	if ( hh < 240.f )
		return m1 + ( m2 - m1 ) * ( 240.f - hh ) / 60.f;
	return m1;
}
static void fxl_from_hls( float h, float l, float s, int cyl, float* o )
{
	float m1, m2;
	if ( s == 0.f )
	{
		o[0] = o[1] = o[2] = l;
		return;
	}
	if ( cyl )
	{
		m2 = l <= 0.5f ? l * ( 1.f + s ) : l + s - l * s;
		m1 = 2.f * l - m2;
	}
	else
	{
		m2 = l + s * 0.5f;
		m1 = l - s * 0.5f;
	}
	o[0] = fxl_calc( m1, m2, h + 120.f ); o[1] = fxl_calc( m1, m2, h ); o[2] = fxl_calc( m1, m2, h - 120.f );
}
static void gfx_fx_soft_hls_adjust( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float huePivot = p[0];
	(void)huePivot;
	float hueScale = p[1];
	(void)hueScale;
	float hueShift = p[2];
	(void)hueShift;
	float ligPivot = p[3];
	(void)ligPivot;
	float ligScale = p[4];
	(void)ligScale;
	float ligShift = p[5];
	(void)ligShift;
	float satPivot = p[6];
	(void)satPivot;
	float satScale = p[7];
	(void)satScale;
	float satShift = p[8];
	(void)satShift;
	int cylindrical = p[9] > 0.5f;
	(void)cylindrical;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float hls[3], rgb[3];
	fxl_to_hls( c, cylindrical, hls );
	if ( hueScale != 1.f || hueShift != 0.f )
	{
		float d = hls[0] - huePivot, h;
		d = d - 360.f * floorf( ( d + 180.f ) / 360.f );
		h = d * hueScale + huePivot + hueShift;
		hls[0] = h - 360.f * floorf( h / 360.f );
	}
	if ( ligScale != 1.f || ligShift != 0.f )
		hls[1] = ( hls[1] - ligPivot ) * ligScale + ligPivot + ligShift;
	if ( satScale != 1.f || satShift != 0.f )
		hls[2] = ( hls[2] - satPivot ) * satScale + satPivot + satShift;
	fxl_from_hls( hls[0], hls[1], hls[2], cylindrical, rgb );
	c[0] = rgb[0]; c[1] = rgb[1]; c[2] = rgb[2];
}

// levels.fx
static float fxlv_a_lv( float v, float inMin, float inMax, float gamma, float outMin, float outMax, int clampSw )
{
	v = inMax == inMin ? inMax : ( v - inMin ) / ( inMax - inMin );
	if ( clampSw || fabsf( outMax - 1.f ) > 1e-6f )
		v = v < 0.f ? 0.f : v > 1.f ? 1.f : v;
	else if ( v < 0.f )
		v = 0.f;
	if ( gamma != 1.f && gamma != 0.f )
	{
		if ( v > 0.f && v < 1.f )
			v = pow_det( v, 1.f / gamma );
		else if ( v > 1.f )
			v = 1.f + ( v - 1.f ) / gamma;
	}
	v = outMin + v * ( outMax - outMin );
	if ( v < 0.f )
		v = 0.f;
	else if ( clampSw && v > 1.f )
		v = 1.f;
	return v;
}
static void gfx_fx_soft_levels( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float inMin = p[0];
	(void)inMin;
	float inMax = p[1];
	(void)inMax;
	float gamma = p[2];
	(void)gamma;
	float outMin = p[3];
	(void)outMin;
	float outMax = p[4];
	(void)outMax;
	int clampSw = p[5] > 0.5f;
	(void)clampSw;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	int i;
	for ( i = 0; i < 3; i++ )
		c[i] = fxlv_a_lv( c[i], inMin, inMax, gamma, outMin, outMax, clampSw );
}

// levels_rgb.fx
static float fxlv_b_lv( float v, float inMin, float inMax, float gamma, float outMin, float outMax, int clampSw )
{
	v = inMax == inMin ? inMax : ( v - inMin ) / ( inMax - inMin );
	if ( clampSw || fabsf( outMax - 1.f ) > 1e-6f )
		v = v < 0.f ? 0.f : v > 1.f ? 1.f : v;
	else if ( v < 0.f )
		v = 0.f;
	if ( gamma != 1.f && gamma != 0.f )
	{
		if ( v > 0.f && v < 1.f )
			v = pow_det( v, 1.f / gamma );
		else if ( v > 1.f )
			v = 1.f + ( v - 1.f ) / gamma;
	}
	v = outMin + v * ( outMax - outMin );
	if ( v < 0.f )
		v = 0.f;
	else if ( clampSw && v > 1.f )
		v = 1.f;
	return v;
}
static void gfx_fx_soft_levels_rgb( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float redInMin = p[0];
	(void)redInMin;
	float redInMax = p[1];
	(void)redInMax;
	float redGamma = p[2];
	(void)redGamma;
	float redOutMin = p[3];
	(void)redOutMin;
	float redOutMax = p[4];
	(void)redOutMax;
	float greenInMin = p[5];
	(void)greenInMin;
	float greenInMax = p[6];
	(void)greenInMax;
	float greenGamma = p[7];
	(void)greenGamma;
	float greenOutMin = p[8];
	(void)greenOutMin;
	float greenOutMax = p[9];
	(void)greenOutMax;
	float blueInMin = p[10];
	(void)blueInMin;
	float blueInMax = p[11];
	(void)blueInMax;
	float blueGamma = p[12];
	(void)blueGamma;
	float blueOutMin = p[13];
	(void)blueOutMin;
	float blueOutMax = p[14];
	(void)blueOutMax;
	int clampSw = p[15] > 0.5f;
	(void)clampSw;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	c[0] = fxlv_b_lv( c[0], redInMin, redInMax, redGamma, redOutMin, redOutMax, clampSw );
	c[1] = fxlv_b_lv( c[1], greenInMin, greenInMax, greenGamma, greenOutMin, greenOutMax, clampSw );
	c[2] = fxlv_b_lv( c[2], blueInMin, blueInMax, blueGamma, blueOutMin, blueOutMax, clampSw );
}

// linear_gradient.fx

static void gfx_fx_soft_linear_gradient( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float centerX = p[0];
	(void)centerX;
	float centerY = p[1];
	(void)centerY;
	float angle = p[2];
	(void)angle;
	float period = p[3];
	(void)period;
	float waveAmp = p[4];
	(void)waveAmp;
	float waveFreq = p[5];
	(void)waveFreq;
	float wavePhase = p[6];
	(void)wavePhase;
	float cycle = p[7];
	(void)cycle;
	const float* color1 = &p[8];
	(void)color1;
	const float* color2 = &p[12];
	(void)color2;
	int curve = (int)floorf( p[16] + 0.5f );
	(void)curve;
	float opacity = p[17];
	(void)opacity;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float cx = centerX * pw;
	float cy = centerY * ph;
	float dx = px - cx;
	float dy = cy - py;
	float a = angle * 0.017453292519943295f;
	float ca = cos_det( a ), sa = sin_det( a );
	float xr = dx * ca + dy * sa;
	float yr = -dx * sa + dy * ca;
	float shift = waveAmp != 0.f ? waveAmp * sin_det( waveFreq * yr + wavePhase ) : 0.f;
	float rad = xr + shift;
	float maxR = period * 0.5f;
	float t = 1.f;
	if ( fabsf( rad ) < maxR )
	{
		t = ( rad + maxR + cycle ) / period;
		t -= floorf( t );
	}
	else if ( rad < 0.f )
		t = 0.f;
	fxc_over( c, color1, color2, fxc_curve( curve, t ), opacity );
}

// radial_gradient.fx

static void gfx_fx_soft_radial_gradient( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float centerX = p[0];
	(void)centerX;
	float centerY = p[1];
	(void)centerY;
	float period = p[2];
	(void)period;
	float innerPeriod = p[3];
	(void)innerPeriod;
	const float* color1 = &p[4];
	(void)color1;
	const float* color2 = &p[8];
	(void)color2;
	int curve = (int)floorf( p[12] + 0.5f );
	(void)curve;
	float opacity = p[13];
	(void)opacity;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float cx = centerX * pw;
	float cy = centerY * ph;
	float dx = px - cx;
	float dy = cy - py;
	float inner = innerPeriod < period ? innerPeriod / period : 0.999999f;
	float r = sqrtf( dx * dx + dy * dy );
	float t = r < period ? r / period : 1.f;
	t = t <= inner ? 0.f : ( t - inner ) / ( 1.f - inner );
	fxc_over( c, color1, color2, fxc_curve( curve, t ), opacity );
}

// square_gradient.fx

static void gfx_fx_soft_square_gradient( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float centerX = p[0];
	(void)centerX;
	float centerY = p[1];
	(void)centerY;
	float size = p[2];
	(void)size;
	const float* color1 = &p[4];
	(void)color1;
	const float* color2 = &p[8];
	(void)color2;
	float opacity = p[12];
	(void)opacity;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float cx = centerX * pw;
	float cy = centerY * ph;
	float dx = px - cx;
	float dy = cy - py;
	float s = ( fabsf( dx ) + fabsf( dy ) ) / size;
	float t = s < 1.f ? s : 1.f;
	fxc_over( c, color1, color2, t, opacity );
}

// diamond_gradient.fx

static void gfx_fx_soft_diamond_gradient( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float centerX = p[0];
	(void)centerX;
	float centerY = p[1];
	(void)centerY;
	float size = p[2];
	(void)size;
	const float* color1 = &p[4];
	(void)color1;
	const float* color2 = &p[8];
	(void)color2;
	float opacity = p[12];
	(void)opacity;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float cx = centerX * pw;
	float cy = centerY * ph;
	float dx = px - cx;
	float dy = cy - py;
	float s = ( fabsf( dx ) / size ) * ( fabsf( dy ) / size );
	float t = s < 1.f ? s : 1.f;
	fxc_over( c, color1, color2, t, opacity );
}

// spin_gradient.fx

static void gfx_fx_soft_spin_gradient( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float centerX = p[0];
	(void)centerX;
	float centerY = p[1];
	(void)centerY;
	float startAngle = p[2];
	(void)startAngle;
	float endAngle = p[3];
	(void)endAngle;
	const float* color1 = &p[4];
	(void)color1;
	const float* color2 = &p[8];
	(void)color2;
	int curve = (int)floorf( p[12] + 0.5f );
	(void)curve;
	float opacity = p[13];
	(void)opacity;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float cx = centerX * pw;
	float cy = centerY * ph;
	float dx = px - cx;
	float dy = cy - py;
	const float PI = 3.14159265358979f;
	float sa = startAngle * ( PI / 180.f ), ea = endAngle * ( PI / 180.f );
	float ang = atan2_det( dy, dx ), pp, range, t;
	sa = sa - 2.f * PI * floorf( ( sa + PI ) / ( 2.f * PI ) );
	ea = ea - 2.f * PI * floorf( ( ea + PI ) / ( 2.f * PI ) );
	pp = ang - sa;
	if ( pp < 0.f )
		pp += 2.f * PI;
	range = ea - sa;
	if ( range <= 0.f )
		range += 2.f * PI;
	t = range >= pp ? pp / range : ( PI + range * 0.5f > pp ? 1.f : 0.f );
	fxc_over( c, color1, color2, fxc_curve( curve, t ), opacity );
}

// four_points_gradient.fx

static void gfx_fx_soft_four_points_gradient( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	float x1 = p[0];
	(void)x1;
	float y1 = p[1];
	(void)y1;
	float x2 = p[2];
	(void)x2;
	float y2 = p[3];
	(void)y2;
	float x3 = p[4];
	(void)x3;
	float y3 = p[5];
	(void)y3;
	float x4 = p[6];
	(void)x4;
	float y4 = p[7];
	(void)y4;
	const float* color1 = &p[8];
	(void)color1;
	const float* color2 = &p[12];
	(void)color2;
	const float* color3 = &p[16];
	(void)color3;
	const float* color4 = &p[20];
	(void)color4;
	float opacity = p[24];
	(void)opacity;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float w[4], ws, pm[3] = { 0.f, 0.f, 0.f }, al = 0.f;
	const float* cols[4];
	int i, k;
	cols[0] = color1; cols[1] = color2; cols[2] = color3; cols[3] = color4;
	{
		float ax[4], ay[4];
		ax[0] = x1; ax[1] = x2; ax[2] = x3; ax[3] = x4;
		ay[0] = y1; ay[1] = y2; ay[2] = y3; ay[3] = y4;
		for ( i = 0; i < 4; i++ )
		{
			float ex = px - ax[i] * pw, ey = py - ay[i] * ph, d = sqrtf( ex * ex + ey * ey );
			w[i] = 1.f / ( d > 0.001f ? d : 0.001f );
		}
	}
	ws = w[0] + w[1] + w[2] + w[3];
	for ( i = 0; i < 4; i++ )
	{
		for ( k = 0; k < 3; k++ )
			pm[k] += cols[i][k] * cols[i][3] * w[i];
		al += cols[i][3] * w[i];
	}
	for ( k = 0; k < 3; k++ )
		pm[k] /= ws;
	fxc_over_pm( c, pm, al / ws, opacity );
}

// lights.fx
static void fxlt_one( float* out, float px, float py, float pw, float ph, float x, float y, float r, float k, const float* col, int curve )
{
	float d, t;
	int i;
	for ( i = 0; i < 3; i++ )
		out[i] = 0.f;
	if ( k <= 0.f || r <= 0.f )
		return;
	d = sqrtf( ( px - x * pw ) * ( px - x * pw ) + ( py - y * ph ) * ( py - y * ph ) ) / ph;
	t = 1.f - d / r;
	t = t < 0.f ? 0.f : t > 1.f ? 1.f : t;
	if ( curve == 1 )
		t = t * t * ( 3.f - 2.f * t );
	else if ( curve == 2 )
		t = t * t;
	for ( i = 0; i < 3; i++ )
		out[i] = col[i] * ( k * t );
}
static void gfx_fx_soft_lights( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	const float* ambient = &p[0];
	(void)ambient;
	int falloff = (int)floorf( p[4] + 0.5f );
	(void)falloff;
	float glow = p[5];
	(void)glow;
	float l1x = p[6];
	(void)l1x;
	float l1y = p[7];
	(void)l1y;
	float l1r = p[8];
	(void)l1r;
	float l1k = p[9];
	(void)l1k;
	const float* l1c = &p[12];
	(void)l1c;
	float l2x = p[16];
	(void)l2x;
	float l2y = p[17];
	(void)l2y;
	float l2r = p[18];
	(void)l2r;
	float l2k = p[19];
	(void)l2k;
	const float* l2c = &p[20];
	(void)l2c;
	float l3x = p[24];
	(void)l3x;
	float l3y = p[25];
	(void)l3y;
	float l3r = p[26];
	(void)l3r;
	float l3k = p[27];
	(void)l3k;
	const float* l3c = &p[28];
	(void)l3c;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float l[3], t[3];
	int i;
	fxlt_one( l, px, py, pw, ph, l1x, l1y, l1r, l1k, l1c, falloff );
	fxlt_one( t, px, py, pw, ph, l2x, l2y, l2r, l2k, l2c, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxlt_one( t, px, py, pw, ph, l3x, l3y, l3r, l3k, l3c, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	for ( i = 0; i < 3; i++ )
		c[i] = c[i] * ( ambient[i] + l[i] ) + l[i] * glow;
}

// spot_light.fx

static void gfx_fx_soft_spot_light( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	const float* ambient = &p[0];
	(void)ambient;
	float x = p[4];
	(void)x;
	float y = p[5];
	(void)y;
	float angle = p[6];
	(void)angle;
	float cone = p[7];
	(void)cone;
	float softness = p[8];
	(void)softness;
	float radius = p[9];
	(void)radius;
	float intensity = p[10];
	(void)intensity;
	int falloff = (int)floorf( p[11] + 0.5f );
	(void)falloff;
	const float* color = &p[12];
	(void)color;
	float glow = p[16];
	(void)glow;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float ex = px - x * pw, ey = y * ph - py;
	float dist = sqrtf( ex * ex + ey * ey );
	float a = angle * 0.017453292519943295f;
	float cosang = dist > 0.f ? ( ex * cos_det( a ) + ey * sin_det( a ) ) / dist : 1.f;
	float c0 = cos_det( cone * 0.017453292519943295f );
	float c1 = cos_det( cone * ( 1.f - softness ) * 0.017453292519943295f );
	float den = c1 - c0, f, t;
	int i;
	den = den > 0.0001f ? den : 0.0001f;
	f = ( cosang - c0 ) / den;
	f = f < 0.f ? 0.f : f > 1.f ? 1.f : f;
	f = f * f * ( 3.f - 2.f * f );
	t = 1.f - dist / ph / radius;
	t = t < 0.f ? 0.f : t > 1.f ? 1.f : t;
	if ( falloff == 1 )
		t = t * t * ( 3.f - 2.f * t );
	else if ( falloff == 2 )
		t = t * t;
	for ( i = 0; i < 3; i++ )
	{
		float l = color[i] * ( intensity * t * f );
		c[i] = c[i] * ( ambient[i] + l ) + l * glow;
	}
}

// scene_lights.fx
static void fxsl_one( float* out, float px, float py, float pw, float ph, float x, float y, float r, float k, const float* col, float ang, float cone, float soft, int kind, int curve )
{
	float ex = px - x * pw, ey = y * ph - py, dist, t;
	int i;
	for ( i = 0; i < 3; i++ )
		out[i] = 0.f;
	if ( k <= 0.f || r <= 0.f )
		return;
	dist = sqrtf( ex * ex + ey * ey );
	t = 1.f - dist / ph / r;
	t = t < 0.f ? 0.f : t > 1.f ? 1.f : t;
	if ( curve == 1 )
		t = t * t * ( 3.f - 2.f * t );
	else if ( curve == 2 )
		t = t * t;
	if ( kind == 1 )
	{
		float a = ang * 0.017453292519943295f, cosang = dist > 0.f ? ( ex * cos_det( a ) + ey * sin_det( a ) ) / dist : 1.f;
		float c0 = cos_det( cone * 0.017453292519943295f ), c1 = cos_det( cone * ( 1.f - soft ) * 0.017453292519943295f ), den = c1 - c0, f;
		den = den > 0.0001f ? den : 0.0001f;
		f = ( cosang - c0 ) / den;
		f = f < 0.f ? 0.f : f > 1.f ? 1.f : f;
		t *= f * f * ( 3.f - 2.f * f );
	}
	for ( i = 0; i < 3; i++ )
		out[i] = col[i] * ( k * t );
}
static void gfx_fx_soft_scene_lights( const float* p, float* c, float u, float v, float px, float py, float pw, float ph )
{
	const float* ambient = &p[0];
	(void)ambient;
	int falloff = (int)floorf( p[4] + 0.5f );
	(void)falloff;
	float glow = p[5];
	(void)glow;
	float exposure = p[6];
	(void)exposure;
	float mixAmt = p[7];
	(void)mixAmt;
	float l0x = p[8];
	(void)l0x;
	float l0y = p[9];
	(void)l0y;
	float l0r = p[10];
	(void)l0r;
	float l0k = p[11];
	(void)l0k;
	const float* l0c = &p[12];
	(void)l0c;
	float l0a = p[16];
	(void)l0a;
	float l0o = p[17];
	(void)l0o;
	float l0s = p[18];
	(void)l0s;
	int l0t = (int)floorf( p[19] + 0.5f );
	(void)l0t;
	float l1x = p[20];
	(void)l1x;
	float l1y = p[21];
	(void)l1y;
	float l1r = p[22];
	(void)l1r;
	float l1k = p[23];
	(void)l1k;
	const float* l1c = &p[24];
	(void)l1c;
	float l1a = p[28];
	(void)l1a;
	float l1o = p[29];
	(void)l1o;
	float l1s = p[30];
	(void)l1s;
	int l1t = (int)floorf( p[31] + 0.5f );
	(void)l1t;
	float l2x = p[32];
	(void)l2x;
	float l2y = p[33];
	(void)l2y;
	float l2r = p[34];
	(void)l2r;
	float l2k = p[35];
	(void)l2k;
	const float* l2c = &p[36];
	(void)l2c;
	float l2a = p[40];
	(void)l2a;
	float l2o = p[41];
	(void)l2o;
	float l2s = p[42];
	(void)l2s;
	int l2t = (int)floorf( p[43] + 0.5f );
	(void)l2t;
	float l3x = p[44];
	(void)l3x;
	float l3y = p[45];
	(void)l3y;
	float l3r = p[46];
	(void)l3r;
	float l3k = p[47];
	(void)l3k;
	const float* l3c = &p[48];
	(void)l3c;
	float l3a = p[52];
	(void)l3a;
	float l3o = p[53];
	(void)l3o;
	float l3s = p[54];
	(void)l3s;
	int l3t = (int)floorf( p[55] + 0.5f );
	(void)l3t;
	float l4x = p[56];
	(void)l4x;
	float l4y = p[57];
	(void)l4y;
	float l4r = p[58];
	(void)l4r;
	float l4k = p[59];
	(void)l4k;
	const float* l4c = &p[60];
	(void)l4c;
	float l4a = p[64];
	(void)l4a;
	float l4o = p[65];
	(void)l4o;
	float l4s = p[66];
	(void)l4s;
	int l4t = (int)floorf( p[67] + 0.5f );
	(void)l4t;
	float l5x = p[68];
	(void)l5x;
	float l5y = p[69];
	(void)l5y;
	float l5r = p[70];
	(void)l5r;
	float l5k = p[71];
	(void)l5k;
	const float* l5c = &p[72];
	(void)l5c;
	float l5a = p[76];
	(void)l5a;
	float l5o = p[77];
	(void)l5o;
	float l5s = p[78];
	(void)l5s;
	int l5t = (int)floorf( p[79] + 0.5f );
	(void)l5t;
	float l6x = p[80];
	(void)l6x;
	float l6y = p[81];
	(void)l6y;
	float l6r = p[82];
	(void)l6r;
	float l6k = p[83];
	(void)l6k;
	const float* l6c = &p[84];
	(void)l6c;
	float l6a = p[88];
	(void)l6a;
	float l6o = p[89];
	(void)l6o;
	float l6s = p[90];
	(void)l6s;
	int l6t = (int)floorf( p[91] + 0.5f );
	(void)l6t;
	float l7x = p[92];
	(void)l7x;
	float l7y = p[93];
	(void)l7y;
	float l7r = p[94];
	(void)l7r;
	float l7k = p[95];
	(void)l7k;
	const float* l7c = &p[96];
	(void)l7c;
	float l7a = p[100];
	(void)l7a;
	float l7o = p[101];
	(void)l7o;
	float l7s = p[102];
	(void)l7s;
	int l7t = (int)floorf( p[103] + 0.5f );
	(void)l7t;
	(void)p;
	(void)u;
	(void)v;
	(void)px;
	(void)py;
	(void)pw;
	(void)ph;
	float l[3] = { 0.f, 0.f, 0.f }, t[3], lit;
	int i;
	fxsl_one( t, px, py, pw, ph, l0x, l0y, l0r, l0k, l0c, l0a, l0o, l0s, l0t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxsl_one( t, px, py, pw, ph, l1x, l1y, l1r, l1k, l1c, l1a, l1o, l1s, l1t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxsl_one( t, px, py, pw, ph, l2x, l2y, l2r, l2k, l2c, l2a, l2o, l2s, l2t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxsl_one( t, px, py, pw, ph, l3x, l3y, l3r, l3k, l3c, l3a, l3o, l3s, l3t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxsl_one( t, px, py, pw, ph, l4x, l4y, l4r, l4k, l4c, l4a, l4o, l4s, l4t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxsl_one( t, px, py, pw, ph, l5x, l5y, l5r, l5k, l5c, l5a, l5o, l5s, l5t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxsl_one( t, px, py, pw, ph, l6x, l6y, l6r, l6k, l6c, l6a, l6o, l6s, l6t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	fxsl_one( t, px, py, pw, ph, l7x, l7y, l7r, l7k, l7c, l7a, l7o, l7s, l7t, falloff );
	for ( i = 0; i < 3; i++ )
		l[i] += t[i];
	for ( i = 0; i < 3; i++ )
	{
		l[i] *= exposure;
		lit = c[i] * ( ambient[i] + l[i] ) + l[i] * glow;
		c[i] = c[i] + ( lit - c[i] ) * mixAmt;
	}
}

typedef void ( *GfxFxSoftFn )( const float* p, float* c, float u, float v, float px, float py, float pw, float ph );
static const GfxFxSoftFn gfx_fx_soft[GFX_FX_ID_MAX + 1] = {
	NULL,
	gfx_fx_soft_bright_contrast,
	gfx_fx_soft_tint,
	gfx_fx_soft_blend,
	gfx_fx_soft_hsv_adjust,
	gfx_fx_soft_hls_adjust,
	gfx_fx_soft_levels,
	gfx_fx_soft_levels_rgb,
	gfx_fx_soft_linear_gradient,
	gfx_fx_soft_radial_gradient,
	gfx_fx_soft_square_gradient,
	gfx_fx_soft_diamond_gradient,
	gfx_fx_soft_spin_gradient,
	gfx_fx_soft_four_points_gradient,
	gfx_fx_soft_lights,
	gfx_fx_soft_spot_light,
	gfx_fx_soft_scene_lights,
};
#endif

#ifdef GFX_FX_WANT_GLSL
static const char* const GFX_FX_VS =
	"#version 300 es\n"
	"void main() {\n"
	"  vec2 p = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));\n"
	"  gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);\n"
	"}\n";
static const char* const gfx_fx_glsl[GFX_FX_ID_MAX + 1] = {
	NULL,
	// bright_contrast
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float brightness = u_p[0].x;\n"
	"  float contrast = u_p[0].y;\n"
	"  float k = contrast < 0.0 ? 1.0 + contrast : 1.0 + 3.0 * contrast;\n"
	"  c.rgb = (c.rgb - 0.5) * k + 0.5 + brightness;\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// tint
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  vec4 color = u_p[0];\n"
	"  float amount = u_p[1].x;\n"
	"  c.rgb = c.rgb * (1.0 - amount) + c.rgb * color.rgb * amount;\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// blend
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"float fxb_burn(float d, float u) { return u <= 0.0 ? 0.0 : 1.0 - min(1.0, (1.0 - d) / u); }\n"
	"float fxb_dodge(float d, float u) { return u >= 1.0 ? 1.0 : min(1.0, d / (1.0 - u)); }\n"
	"float fxb_screen(float d, float u) { return 1.0 - (1.0 - d) * (1.0 - u); }\n"
	"float fxb_ch(int m, float d, float u) {\n"
	"  if (m == 0) return u;\n"
	"  if (m == 1) return d * u;\n"
	"  if (m == 2) return u <= 0.0 ? 1.0 : d / u;\n"
	"  if (m == 3) return fxb_burn(d, u);\n"
	"  if (m == 4) return clamp(d + u - 1.0, 0.0, 1.0);\n"
	"  if (m == 5) return min(d, u);\n"
	"  if (m == 7) return max(d, u);\n"
	"  if (m == 8) return fxb_screen(d, u);\n"
	"  if (m == 9) return fxb_dodge(d, u);\n"
	"  if (m == 10) return min(1.0, d + u);\n"
	"  if (m == 12) return d < 0.5 ? u * (2.0 * d) : fxb_screen(u, 2.0 * d - 1.0);\n"
	"  if (m == 13) {\n"
	"    if (u < 0.5) return d + (d - d * d) * (2.0 * u - 1.0);\n"
	"    if (d < 0.25) return d + (2.0 * u - 1.0) * (((16.0 * d - 12.0) * d + 4.0) * d - d);\n"
	"    return d + (2.0 * u - 1.0) * (sqrt(d) - d);\n"
	"  }\n"
	"  if (m == 14) return u < 0.5 ? d * (2.0 * u) : fxb_screen(d, 2.0 * u - 1.0);\n"
	"  if (m == 15) return u < 0.5 ? fxb_burn(d, 2.0 * u) : fxb_dodge(d, 2.0 * u - 1.0);\n"
	"  if (m == 16) return u < 0.5 ? clamp(d + 2.0 * u - 1.0, 0.0, 1.0) : min(1.0, d + 2.0 * u - 1.0);\n"
	"  if (m == 17) return u < 0.5 ? min(2.0 * u, d) : max(2.0 * u - 1.0, d);\n"
	"  return (u < 0.5 ? fxb_burn(d, 2.0 * u) : fxb_dodge(d, 2.0 * u - 1.0)) < 0.5 ? 0.0 : 1.0;\n"
	"}\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  int mode = int(floor(u_p[0].x + 0.5));\n"
	"  vec4 color = u_p[1];\n"
	"  float opacity = u_p[2].x;\n"
	"  vec3 up = color.rgb;\n"
	"  vec3 b;\n"
	"  if (mode == 6 || mode == 11) {\n"
	"    float ld = dot(c.rgb, vec3(0.298912, 0.586611, 0.114478));\n"
	"    float lu = dot(up, vec3(0.298912, 0.586611, 0.114478));\n"
	"    bool upWins = mode == 6 ? !(ld < lu) : ld < lu;\n"
	"    b = upWins ? up : c.rgb;\n"
	"  } else {\n"
	"    b = vec3(fxb_ch(mode, c.r, up.r), fxb_ch(mode, c.g, up.g), fxb_ch(mode, c.b, up.b));\n"
	"  }\n"
	"  c.rgb = mix(c.rgb, b, color.a * opacity);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// hsv_adjust
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"vec3 fxh_to_hsv(vec3 c) {\n"
	"  float mx = max(c.r, max(c.g, c.b)), mn = min(c.r, min(c.g, c.b));\n"
	"  float h = 0.0, s = 0.0, d = mx - mn;\n"
	"  if (mx != mn) {\n"
	"    s = d / mx;\n"
	"    if (c.r == mx) h = (c.g - c.b) / d;\n"
	"    else if (c.g == mx) h = 2.0 + (c.b - c.r) / d;\n"
	"    else h = 4.0 + (c.r - c.g) / d;\n"
	"    h *= 60.0;\n"
	"    if (h < 0.0) h += 360.0;\n"
	"  }\n"
	"  return vec3(h, s, mx);\n"
	"}\n"
	"vec3 fxh_from_hsv(float h, float s, float v) {\n"
	"  if (s == 0.0) return vec3(v);\n"
	"  float hh = (h - 360.0 * floor(h / 360.0)) / 60.0;\n"
	"  if (hh >= 6.0) hh -= 6.0;\n"
	"  float i = floor(hh), f = hh - i;\n"
	"  float p = v * (1.0 - s), q = v * (1.0 - s * f), t = v * (1.0 - s * (1.0 - f));\n"
	"  int k = int(i);\n"
	"  if (k == 0) return vec3(v, t, p);\n"
	"  if (k == 1) return vec3(q, v, p);\n"
	"  if (k == 2) return vec3(p, v, t);\n"
	"  if (k == 3) return vec3(p, q, v);\n"
	"  if (k == 4) return vec3(t, p, v);\n"
	"  return vec3(v, p, q);\n"
	"}\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float huePivot = u_p[0].x;\n"
	"  float hueScale = u_p[0].y;\n"
	"  float hueShift = u_p[0].z;\n"
	"  float valPivot = u_p[0].w;\n"
	"  float valScale = u_p[1].x;\n"
	"  float valShift = u_p[1].y;\n"
	"  float satPivot = u_p[1].z;\n"
	"  float satScale = u_p[1].w;\n"
	"  float satShift = u_p[2].x;\n"
	"  vec3 hsv = fxh_to_hsv(c.rgb);\n"
	"  if (hueScale != 1.0 || hueShift != 0.0) {\n"
	"    float d = hsv.x - huePivot;\n"
	"    d = d - 360.0 * floor((d + 180.0) / 360.0);\n"
	"    float h = d * hueScale + huePivot + hueShift;\n"
	"    hsv.x = h - 360.0 * floor(h / 360.0);\n"
	"  }\n"
	"  if (satScale != 1.0 || satShift != 0.0) hsv.y = max(0.0, (hsv.y - satPivot) * satScale + satPivot + satShift);\n"
	"  if (valScale != 1.0 || valShift != 0.0) hsv.z = (hsv.z - valPivot) * valScale + valPivot + valShift;\n"
	"  c.rgb = fxh_from_hsv(hsv.x, hsv.y, hsv.z);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// hls_adjust
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"vec3 fxl_to_hls(vec3 c, bool cyl) {\n"
	"  float mx = max(c.r, max(c.g, c.b)), mn = min(c.r, min(c.g, c.b));\n"
	"  float h = 0.0, s = 0.0, l = (mx + mn) / 2.0;\n"
	"  if (mx != mn) {\n"
	"    float d = mx - mn;\n"
	"    if (cyl) s = l <= 0.5 ? d / (mx + mn) : d / (2.0 - (mx + mn));\n"
	"    else s = d;\n"
	"    float rm = (mx - c.r) / d, gm = (mx - c.g) / d, bm = (mx - c.b) / d;\n"
	"    if (c.r == mx) h = bm - gm;\n"
	"    else if (c.g == mx) h = 2.0 + rm - bm;\n"
	"    else h = 4.0 + gm - rm;\n"
	"    h *= 60.0;\n"
	"    if (h < 0.0) h += 360.0;\n"
	"  }\n"
	"  return vec3(h, l, s);\n"
	"}\n"
	"float fxl_calc(float m1, float m2, float hue) {\n"
	"  float hh = hue - 360.0 * floor(hue / 360.0);\n"
	"  if (hh < 60.0) return m1 + (m2 - m1) * hh / 60.0;\n"
	"  if (hh < 180.0) return m2;\n"
	"  if (hh < 240.0) return m1 + (m2 - m1) * (240.0 - hh) / 60.0;\n"
	"  return m1;\n"
	"}\n"
	"vec3 fxl_from_hls(float h, float l, float s, bool cyl) {\n"
	"  if (s == 0.0) return vec3(l);\n"
	"  float m2, m1;\n"
	"  if (cyl) {\n"
	"    m2 = l <= 0.5 ? l * (1.0 + s) : l + s - l * s;\n"
	"    m1 = 2.0 * l - m2;\n"
	"  } else {\n"
	"    m2 = l + s * 0.5;\n"
	"    m1 = l - s * 0.5;\n"
	"  }\n"
	"  return vec3(fxl_calc(m1, m2, h + 120.0), fxl_calc(m1, m2, h), fxl_calc(m1, m2, h - 120.0));\n"
	"}\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float huePivot = u_p[0].x;\n"
	"  float hueScale = u_p[0].y;\n"
	"  float hueShift = u_p[0].z;\n"
	"  float ligPivot = u_p[0].w;\n"
	"  float ligScale = u_p[1].x;\n"
	"  float ligShift = u_p[1].y;\n"
	"  float satPivot = u_p[1].z;\n"
	"  float satScale = u_p[1].w;\n"
	"  float satShift = u_p[2].x;\n"
	"  bool cylindrical = u_p[2].y > 0.5;\n"
	"  vec3 hls = fxl_to_hls(c.rgb, cylindrical);\n"
	"  if (hueScale != 1.0 || hueShift != 0.0) {\n"
	"    float d = hls.x - huePivot;\n"
	"    d = d - 360.0 * floor((d + 180.0) / 360.0);\n"
	"    float h = d * hueScale + huePivot + hueShift;\n"
	"    hls.x = h - 360.0 * floor(h / 360.0);\n"
	"  }\n"
	"  if (ligScale != 1.0 || ligShift != 0.0) hls.y = (hls.y - ligPivot) * ligScale + ligPivot + ligShift;\n"
	"  if (satScale != 1.0 || satShift != 0.0) hls.z = (hls.z - satPivot) * satScale + satPivot + satShift;\n"
	"  c.rgb = fxl_from_hls(hls.x, hls.y, hls.z, cylindrical);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// levels
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"float fxlv_a_lv(float v, float inMin, float inMax, float gamma, float outMin, float outMax, bool clampSw) {\n"
	"  v = inMax == inMin ? inMax : (v - inMin) / (inMax - inMin);\n"
	"  if (clampSw || abs(outMax - 1.0) > 1e-6) v = clamp(v, 0.0, 1.0); else v = max(v, 0.0);\n"
	"  if (gamma != 1.0 && gamma != 0.0) {\n"
	"    if (v > 0.0 && v < 1.0) v = pow(v, 1.0 / gamma);\n"
	"    else if (v > 1.0) v = 1.0 + (v - 1.0) / gamma;\n"
	"  }\n"
	"  v = outMin + v * (outMax - outMin);\n"
	"  return clampSw ? clamp(v, 0.0, 1.0) : max(v, 0.0);\n"
	"}\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float inMin = u_p[0].x;\n"
	"  float inMax = u_p[0].y;\n"
	"  float gamma = u_p[0].z;\n"
	"  float outMin = u_p[0].w;\n"
	"  float outMax = u_p[1].x;\n"
	"  bool clampSw = u_p[1].y > 0.5;\n"
	"  c.rgb = vec3(fxlv_a_lv(c.r, inMin, inMax, gamma, outMin, outMax, clampSw), fxlv_a_lv(c.g, inMin, inMax, gamma, outMin, outMax, clampSw), fxlv_a_lv(c.b, inMin, inMax, gamma, outMin, outMax, clampSw));\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// levels_rgb
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"float fxlv_b_lv(float v, float inMin, float inMax, float gamma, float outMin, float outMax, bool clampSw) {\n"
	"  v = inMax == inMin ? inMax : (v - inMin) / (inMax - inMin);\n"
	"  if (clampSw || abs(outMax - 1.0) > 1e-6) v = clamp(v, 0.0, 1.0); else v = max(v, 0.0);\n"
	"  if (gamma != 1.0 && gamma != 0.0) {\n"
	"    if (v > 0.0 && v < 1.0) v = pow(v, 1.0 / gamma);\n"
	"    else if (v > 1.0) v = 1.0 + (v - 1.0) / gamma;\n"
	"  }\n"
	"  v = outMin + v * (outMax - outMin);\n"
	"  return clampSw ? clamp(v, 0.0, 1.0) : max(v, 0.0);\n"
	"}\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float redInMin = u_p[0].x;\n"
	"  float redInMax = u_p[0].y;\n"
	"  float redGamma = u_p[0].z;\n"
	"  float redOutMin = u_p[0].w;\n"
	"  float redOutMax = u_p[1].x;\n"
	"  float greenInMin = u_p[1].y;\n"
	"  float greenInMax = u_p[1].z;\n"
	"  float greenGamma = u_p[1].w;\n"
	"  float greenOutMin = u_p[2].x;\n"
	"  float greenOutMax = u_p[2].y;\n"
	"  float blueInMin = u_p[2].z;\n"
	"  float blueInMax = u_p[2].w;\n"
	"  float blueGamma = u_p[3].x;\n"
	"  float blueOutMin = u_p[3].y;\n"
	"  float blueOutMax = u_p[3].z;\n"
	"  bool clampSw = u_p[3].w > 0.5;\n"
	"  c.rgb = vec3(fxlv_b_lv(c.r, redInMin, redInMax, redGamma, redOutMin, redOutMax, clampSw), fxlv_b_lv(c.g, greenInMin, greenInMax, greenGamma, greenOutMin, greenOutMax, clampSw), fxlv_b_lv(c.b, blueInMin, blueInMax, blueGamma, blueOutMin, blueOutMax, clampSw));\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// linear_gradient
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float centerX = u_p[0].x;\n"
	"  float centerY = u_p[0].y;\n"
	"  float angle = u_p[0].z;\n"
	"  float period = u_p[0].w;\n"
	"  float waveAmp = u_p[1].x;\n"
	"  float waveFreq = u_p[1].y;\n"
	"  float wavePhase = u_p[1].z;\n"
	"  float cycle = u_p[1].w;\n"
	"  vec4 color1 = u_p[2];\n"
	"  vec4 color2 = u_p[3];\n"
	"  int curve = int(floor(u_p[4].x + 0.5));\n"
	"  float opacity = u_p[4].y;\n"
	"  float cx = centerX * pw;\n"
	"  float cy = centerY * ph;\n"
	"  float dx = px - cx;\n"
	"  float dy = cy - py;\n"
	"  float a = radians(angle);\n"
	"  float xr = dx * cos(a) + dy * sin(a);\n"
	"  float yr = -dx * sin(a) + dy * cos(a);\n"
	"  float shift = waveAmp != 0.0 ? waveAmp * sin(waveFreq * yr + wavePhase) : 0.0;\n"
	"  float rad = xr + shift;\n"
	"  float maxR = period * 0.5;\n"
	"  float t = 1.0;\n"
	"  if (abs(rad) < maxR) { t = (rad + maxR + cycle) / period; t -= floor(t); }\n"
	"  else if (rad < 0.0) t = 0.0;\n"
	"  c = fxc_over(c, color1, color2, fxc_curve(curve, t), opacity);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// radial_gradient
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float centerX = u_p[0].x;\n"
	"  float centerY = u_p[0].y;\n"
	"  float period = u_p[0].z;\n"
	"  float innerPeriod = u_p[0].w;\n"
	"  vec4 color1 = u_p[1];\n"
	"  vec4 color2 = u_p[2];\n"
	"  int curve = int(floor(u_p[3].x + 0.5));\n"
	"  float opacity = u_p[3].y;\n"
	"  float cx = centerX * pw;\n"
	"  float cy = centerY * ph;\n"
	"  float dx = px - cx;\n"
	"  float dy = cy - py;\n"
	"  float inner = innerPeriod < period ? innerPeriod / period : 0.999999;\n"
	"  float r = sqrt(dx * dx + dy * dy);\n"
	"  float t = r < period ? r / period : 1.0;\n"
	"  t = t <= inner ? 0.0 : (t - inner) / (1.0 - inner);\n"
	"  c = fxc_over(c, color1, color2, fxc_curve(curve, t), opacity);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// square_gradient
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float centerX = u_p[0].x;\n"
	"  float centerY = u_p[0].y;\n"
	"  float size = u_p[0].z;\n"
	"  vec4 color1 = u_p[1];\n"
	"  vec4 color2 = u_p[2];\n"
	"  float opacity = u_p[3].x;\n"
	"  float cx = centerX * pw;\n"
	"  float cy = centerY * ph;\n"
	"  float dx = px - cx;\n"
	"  float dy = cy - py;\n"
	"  float s = (abs(dx) + abs(dy)) / size;\n"
	"  float t = s < 1.0 ? s : 1.0;\n"
	"  c = fxc_over(c, color1, color2, t, opacity);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// diamond_gradient
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float centerX = u_p[0].x;\n"
	"  float centerY = u_p[0].y;\n"
	"  float size = u_p[0].z;\n"
	"  vec4 color1 = u_p[1];\n"
	"  vec4 color2 = u_p[2];\n"
	"  float opacity = u_p[3].x;\n"
	"  float cx = centerX * pw;\n"
	"  float cy = centerY * ph;\n"
	"  float dx = px - cx;\n"
	"  float dy = cy - py;\n"
	"  float s = (abs(dx) / size) * (abs(dy) / size);\n"
	"  float t = s < 1.0 ? s : 1.0;\n"
	"  c = fxc_over(c, color1, color2, t, opacity);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// spin_gradient
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float centerX = u_p[0].x;\n"
	"  float centerY = u_p[0].y;\n"
	"  float startAngle = u_p[0].z;\n"
	"  float endAngle = u_p[0].w;\n"
	"  vec4 color1 = u_p[1];\n"
	"  vec4 color2 = u_p[2];\n"
	"  int curve = int(floor(u_p[3].x + 0.5));\n"
	"  float opacity = u_p[3].y;\n"
	"  float cx = centerX * pw;\n"
	"  float cy = centerY * ph;\n"
	"  float dx = px - cx;\n"
	"  float dy = cy - py;\n"
	"  const float PI = 3.14159265358979;\n"
	"  float sa = radians(startAngle), ea = radians(endAngle);\n"
	"  sa = sa - 2.0 * PI * floor((sa + PI) / (2.0 * PI));\n"
	"  ea = ea - 2.0 * PI * floor((ea + PI) / (2.0 * PI));\n"
	"  float ang = atan(dy, dx);\n"
	"  float p = ang - sa;\n"
	"  if (p < 0.0) p += 2.0 * PI;\n"
	"  float range = ea - sa;\n"
	"  if (range <= 0.0) range += 2.0 * PI;\n"
	"  float t = range >= p ? p / range : (PI + range * 0.5 > p ? 1.0 : 0.0);\n"
	"  c = fxc_over(c, color1, color2, fxc_curve(curve, t), opacity);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// four_points_gradient
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  float x1 = u_p[0].x;\n"
	"  float y1 = u_p[0].y;\n"
	"  float x2 = u_p[0].z;\n"
	"  float y2 = u_p[0].w;\n"
	"  float x3 = u_p[1].x;\n"
	"  float y3 = u_p[1].y;\n"
	"  float x4 = u_p[1].z;\n"
	"  float y4 = u_p[1].w;\n"
	"  vec4 color1 = u_p[2];\n"
	"  vec4 color2 = u_p[3];\n"
	"  vec4 color3 = u_p[4];\n"
	"  vec4 color4 = u_p[5];\n"
	"  float opacity = u_p[6].x;\n"
	"  float w1 = 1.0 / max(length(vec2(px - x1 * pw, py - y1 * ph)), 0.001);\n"
	"  float w2 = 1.0 / max(length(vec2(px - x2 * pw, py - y2 * ph)), 0.001);\n"
	"  float w3 = 1.0 / max(length(vec2(px - x3 * pw, py - y3 * ph)), 0.001);\n"
	"  float w4 = 1.0 / max(length(vec2(px - x4 * pw, py - y4 * ph)), 0.001);\n"
	"  float ws = w1 + w2 + w3 + w4;\n"
	"  vec3 pm = (color1.rgb * color1.a * w1 + color2.rgb * color2.a * w2 + color3.rgb * color3.a * w3 + color4.rgb * color4.a * w4) / ws;\n"
	"  float al = (color1.a * w1 + color2.a * w2 + color3.a * w3 + color4.a * w4) / ws;\n"
	"  c = fxc_over_pm(c, pm, al, opacity);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// lights
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"vec3 fxlt_one(float px, float py, float pw, float ph, float x, float y, float r, float k, vec4 col, int curve) {\n"
	"  if (k <= 0.0 || r <= 0.0) return vec3(0.0);\n"
	"  float d = length(vec2(px - x * pw, py - y * ph)) / ph;\n"
	"  float t = clamp(1.0 - d / r, 0.0, 1.0);\n"
	"  if (curve == 1) t = t * t * (3.0 - 2.0 * t); else if (curve == 2) t = t * t;\n"
	"  return col.rgb * (k * t);\n"
	"}\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  vec4 ambient = u_p[0];\n"
	"  int falloff = int(floor(u_p[1].x + 0.5));\n"
	"  float glow = u_p[1].y;\n"
	"  float l1x = u_p[1].z;\n"
	"  float l1y = u_p[1].w;\n"
	"  float l1r = u_p[2].x;\n"
	"  float l1k = u_p[2].y;\n"
	"  vec4 l1c = u_p[3];\n"
	"  float l2x = u_p[4].x;\n"
	"  float l2y = u_p[4].y;\n"
	"  float l2r = u_p[4].z;\n"
	"  float l2k = u_p[4].w;\n"
	"  vec4 l2c = u_p[5];\n"
	"  float l3x = u_p[6].x;\n"
	"  float l3y = u_p[6].y;\n"
	"  float l3r = u_p[6].z;\n"
	"  float l3k = u_p[6].w;\n"
	"  vec4 l3c = u_p[7];\n"
	"  vec3 l = fxlt_one(px, py, pw, ph, l1x, l1y, l1r, l1k, l1c, falloff) + fxlt_one(px, py, pw, ph, l2x, l2y, l2r, l2k, l2c, falloff) + fxlt_one(px, py, pw, ph, l3x, l3y, l3r, l3k, l3c, falloff);\n"
	"  c.rgb = c.rgb * (ambient.rgb + l) + l * glow;\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// spot_light
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  vec4 ambient = u_p[0];\n"
	"  float x = u_p[1].x;\n"
	"  float y = u_p[1].y;\n"
	"  float angle = u_p[1].z;\n"
	"  float cone = u_p[1].w;\n"
	"  float softness = u_p[2].x;\n"
	"  float radius = u_p[2].y;\n"
	"  float intensity = u_p[2].z;\n"
	"  int falloff = int(floor(u_p[2].w + 0.5));\n"
	"  vec4 color = u_p[3];\n"
	"  float glow = u_p[4].x;\n"
	"  float ex = px - x * pw;\n"
	"  float ey = y * ph - py;\n"
	"  float dist = length(vec2(ex, ey));\n"
	"  float a = radians(angle);\n"
	"  float cosang = dist > 0.0 ? (ex * cos(a) + ey * sin(a)) / dist : 1.0;\n"
	"  float c0 = cos(radians(cone));\n"
	"  float c1 = cos(radians(cone * (1.0 - softness)));\n"
	"  float f = clamp((cosang - c0) / max(c1 - c0, 0.0001), 0.0, 1.0);\n"
	"  f = f * f * (3.0 - 2.0 * f);\n"
	"  float t = clamp(1.0 - dist / ph / radius, 0.0, 1.0);\n"
	"  if (falloff == 1) t = t * t * (3.0 - 2.0 * t); else if (falloff == 2) t = t * t;\n"
	"  vec3 l = color.rgb * (intensity * t * f);\n"
	"  c.rgb = c.rgb * (ambient.rgb + l) + l * glow;\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
	// scene_lights
	"#version 300 es\n"
	"precision highp float;\n"
	"precision highp int;\n"
	"uniform sampler2D u_src;\n"
	"uniform vec4 u_p[32];\n"
	"uniform vec4 u_size;\n"
	"layout(location = 0) out vec4 frag;\n"
	"float fxc_curve(int ty, float t) {\n"
	"  if (ty == 1) return t;\n"
	"  if (ty == 2) return t * t;\n"
	"  if (ty == 3) return 1.0 - (1.0 - t) * (1.0 - t);\n"
	"  return (-2.0 * t + 3.0) * (t * t);\n"
	"}\n"
	"vec4 fxc_over_pm(vec4 c, vec3 pm, float a, float op) { return vec4(pm * op + c.rgb * (1.0 - a * op), c.a); }\n"
	"vec4 fxc_over(vec4 c, vec4 c1, vec4 c2, float f, float op) {\n"
	"  return fxc_over_pm(c, c1.rgb * c1.a * (1.0 - f) + c2.rgb * c2.a * f, c1.a * (1.0 - f) + c2.a * f, op);\n"
	"}\n"
	"vec3 fxsl_one(float px, float py, float pw, float ph, float x, float y, float r, float k, vec4 col, float ang, float cone, float soft, int kind, int curve) {\n"
	"  if (k <= 0.0 || r <= 0.0) return vec3(0.0);\n"
	"  float ex = px - x * pw, ey = y * ph - py;\n"
	"  float dist = length(vec2(ex, ey));\n"
	"  float t = clamp(1.0 - dist / ph / r, 0.0, 1.0);\n"
	"  if (curve == 1) t = t * t * (3.0 - 2.0 * t); else if (curve == 2) t = t * t;\n"
	"  if (kind == 1) {\n"
	"    float a = radians(ang);\n"
	"    float cosang = dist > 0.0 ? (ex * cos(a) + ey * sin(a)) / dist : 1.0;\n"
	"    float c0 = cos(radians(cone)), c1 = cos(radians(cone * (1.0 - soft)));\n"
	"    float f = clamp((cosang - c0) / max(c1 - c0, 0.0001), 0.0, 1.0);\n"
	"    t *= f * f * (3.0 - 2.0 * f);\n"
	"  }\n"
	"  return col.rgb * (k * t);\n"
	"}\n"
	"vec4 fx(vec4 c, vec2 uv, float px, float py, float pw, float ph) {\n"
	"  vec4 ambient = u_p[0];\n"
	"  int falloff = int(floor(u_p[1].x + 0.5));\n"
	"  float glow = u_p[1].y;\n"
	"  float exposure = u_p[1].z;\n"
	"  float mixAmt = u_p[1].w;\n"
	"  float l0x = u_p[2].x;\n"
	"  float l0y = u_p[2].y;\n"
	"  float l0r = u_p[2].z;\n"
	"  float l0k = u_p[2].w;\n"
	"  vec4 l0c = u_p[3];\n"
	"  float l0a = u_p[4].x;\n"
	"  float l0o = u_p[4].y;\n"
	"  float l0s = u_p[4].z;\n"
	"  int l0t = int(floor(u_p[4].w + 0.5));\n"
	"  float l1x = u_p[5].x;\n"
	"  float l1y = u_p[5].y;\n"
	"  float l1r = u_p[5].z;\n"
	"  float l1k = u_p[5].w;\n"
	"  vec4 l1c = u_p[6];\n"
	"  float l1a = u_p[7].x;\n"
	"  float l1o = u_p[7].y;\n"
	"  float l1s = u_p[7].z;\n"
	"  int l1t = int(floor(u_p[7].w + 0.5));\n"
	"  float l2x = u_p[8].x;\n"
	"  float l2y = u_p[8].y;\n"
	"  float l2r = u_p[8].z;\n"
	"  float l2k = u_p[8].w;\n"
	"  vec4 l2c = u_p[9];\n"
	"  float l2a = u_p[10].x;\n"
	"  float l2o = u_p[10].y;\n"
	"  float l2s = u_p[10].z;\n"
	"  int l2t = int(floor(u_p[10].w + 0.5));\n"
	"  float l3x = u_p[11].x;\n"
	"  float l3y = u_p[11].y;\n"
	"  float l3r = u_p[11].z;\n"
	"  float l3k = u_p[11].w;\n"
	"  vec4 l3c = u_p[12];\n"
	"  float l3a = u_p[13].x;\n"
	"  float l3o = u_p[13].y;\n"
	"  float l3s = u_p[13].z;\n"
	"  int l3t = int(floor(u_p[13].w + 0.5));\n"
	"  float l4x = u_p[14].x;\n"
	"  float l4y = u_p[14].y;\n"
	"  float l4r = u_p[14].z;\n"
	"  float l4k = u_p[14].w;\n"
	"  vec4 l4c = u_p[15];\n"
	"  float l4a = u_p[16].x;\n"
	"  float l4o = u_p[16].y;\n"
	"  float l4s = u_p[16].z;\n"
	"  int l4t = int(floor(u_p[16].w + 0.5));\n"
	"  float l5x = u_p[17].x;\n"
	"  float l5y = u_p[17].y;\n"
	"  float l5r = u_p[17].z;\n"
	"  float l5k = u_p[17].w;\n"
	"  vec4 l5c = u_p[18];\n"
	"  float l5a = u_p[19].x;\n"
	"  float l5o = u_p[19].y;\n"
	"  float l5s = u_p[19].z;\n"
	"  int l5t = int(floor(u_p[19].w + 0.5));\n"
	"  float l6x = u_p[20].x;\n"
	"  float l6y = u_p[20].y;\n"
	"  float l6r = u_p[20].z;\n"
	"  float l6k = u_p[20].w;\n"
	"  vec4 l6c = u_p[21];\n"
	"  float l6a = u_p[22].x;\n"
	"  float l6o = u_p[22].y;\n"
	"  float l6s = u_p[22].z;\n"
	"  int l6t = int(floor(u_p[22].w + 0.5));\n"
	"  float l7x = u_p[23].x;\n"
	"  float l7y = u_p[23].y;\n"
	"  float l7r = u_p[23].z;\n"
	"  float l7k = u_p[23].w;\n"
	"  vec4 l7c = u_p[24];\n"
	"  float l7a = u_p[25].x;\n"
	"  float l7o = u_p[25].y;\n"
	"  float l7s = u_p[25].z;\n"
	"  int l7t = int(floor(u_p[25].w + 0.5));\n"
	"  vec3 l = fxsl_one(px, py, pw, ph, l0x, l0y, l0r, l0k, l0c, l0a, l0o, l0s, l0t, falloff) + fxsl_one(px, py, pw, ph, l1x, l1y, l1r, l1k, l1c, l1a, l1o, l1s, l1t, falloff) + fxsl_one(px, py, pw, ph, l2x, l2y, l2r, l2k, l2c, l2a, l2o, l2s, l2t, falloff) + fxsl_one(px, py, pw, ph, l3x, l3y, l3r, l3k, l3c, l3a, l3o, l3s, l3t, falloff) + fxsl_one(px, py, pw, ph, l4x, l4y, l4r, l4k, l4c, l4a, l4o, l4s, l4t, falloff) + fxsl_one(px, py, pw, ph, l5x, l5y, l5r, l5k, l5c, l5a, l5o, l5s, l5t, falloff) + fxsl_one(px, py, pw, ph, l6x, l6y, l6r, l6k, l6c, l6a, l6o, l6s, l6t, falloff) + fxsl_one(px, py, pw, ph, l7x, l7y, l7r, l7k, l7c, l7a, l7o, l7s, l7t, falloff);\n"
	"  l *= exposure;\n"
	"  c.rgb = mix(c.rgb, c.rgb * (ambient.rgb + l) + l * glow, mixAmt);\n"
	"  return c;\n"
	"}\n"
	"void main() {\n"
	"  vec4 c = texelFetch(u_src, ivec2(gl_FragCoord.xy), 0);\n"
	"  float py = u_size.y - gl_FragCoord.y;\n"
	"  frag = fx(c, vec2(gl_FragCoord.x, py) / u_size.xy, gl_FragCoord.x, py, u_size.x, u_size.y);\n"
	"}\n",
};
#endif

#endif
