"""fxdefs.py: GENERATED by tools/gfx_fx_gen.py from src/native/gfx2d/fx/*.fx. Do not edit: change the .fx and run the tool.

EFFECTS maps an effect's name to its id (what gfx_effect takes), its title, its menu group and its parameters; each parameter says its type, its place in
the float block (offset, size), its range, its default (a list: four numbers for a color) and, for an enum, its options."""
import json

PARAM_FLOATS = 128

EFFECTS = json.loads(r'''
{
 "blend": {
  "group": "Blend",
  "hidden": false,
  "id": 3,
  "nparams": 9,
  "params": [
   {
    "default": [
     1.0
    ],
    "label": "Mode",
    "max": 18.0,
    "min": 0.0,
    "name": "mode",
    "offset": 0,
    "options": [
     "Normal",
     "Multiply",
     "Divide",
     "ColorBurn",
     "LinearBurn",
     "Darken",
     "DarkerColor",
     "Lighten",
     "Screen",
     "ColorDodge",
     "LinearDodge",
     "LighterColor",
     "Overlay",
     "SoftLight",
     "HardLight",
     "VividLight",
     "LinearLight",
     "PinLight",
     "HardMix"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     1.0,
     0.5,
     0.1,
     1.0
    ],
    "label": "Color",
    "max": 1.0,
    "min": 0.0,
    "name": "color",
    "offset": 4,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Opacity",
    "max": 1.0,
    "min": 0.0,
    "name": "opacity",
    "offset": 8,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Blend Color"
 },
 "bright_contrast": {
  "group": "Color",
  "hidden": false,
  "id": 1,
  "nparams": 2,
  "params": [
   {
    "default": [
     0.0
    ],
    "label": "Brightness",
    "max": 1.0,
    "min": -1.0,
    "name": "brightness",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Contrast",
    "max": 1.0,
    "min": -1.0,
    "name": "contrast",
    "offset": 1,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Brightness / Contrast"
 },
 "diamond_gradient": {
  "group": "Gradient",
  "hidden": false,
  "id": 11,
  "nparams": 13,
  "params": [
   {
    "default": [
     0.5
    ],
    "label": "Center X",
    "max": 1.0,
    "min": 0.0,
    "name": "centerX",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Center Y",
    "max": 1.0,
    "min": 0.0,
    "name": "centerY",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     100.0
    ],
    "label": "Size",
    "max": 10000.0,
    "min": 1.0,
    "name": "size",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     1.0,
     1.0,
     1.0
    ],
    "label": "Color 1",
    "max": 1.0,
    "min": 0.0,
    "name": "color1",
    "offset": 4,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.0,
     0.0,
     0.0,
     1.0
    ],
    "label": "Color 2",
    "max": 1.0,
    "min": 0.0,
    "name": "color2",
    "offset": 8,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Opacity",
    "max": 1.0,
    "min": 0.0,
    "name": "opacity",
    "offset": 12,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Diamond Gradient"
 },
 "four_points_gradient": {
  "group": "Gradient",
  "hidden": false,
  "id": 13,
  "nparams": 25,
  "params": [
   {
    "default": [
     0.9
    ],
    "label": "Point 1 X",
    "max": 1.0,
    "min": 0.0,
    "name": "x1",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.1
    ],
    "label": "Point 1 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "y1",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.1
    ],
    "label": "Point 2 X",
    "max": 1.0,
    "min": 0.0,
    "name": "x2",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.1
    ],
    "label": "Point 2 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "y2",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.1
    ],
    "label": "Point 3 X",
    "max": 1.0,
    "min": 0.0,
    "name": "x3",
    "offset": 4,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.9
    ],
    "label": "Point 3 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "y3",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.9
    ],
    "label": "Point 4 X",
    "max": 1.0,
    "min": 0.0,
    "name": "x4",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.9
    ],
    "label": "Point 4 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "y4",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.0,
     0.0,
     1.0
    ],
    "label": "Color 1",
    "max": 1.0,
    "min": 0.0,
    "name": "color1",
    "offset": 8,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.0,
     1.0,
     0.0,
     1.0
    ],
    "label": "Color 2",
    "max": 1.0,
    "min": 0.0,
    "name": "color2",
    "offset": 12,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.0,
     0.0,
     1.0,
     1.0
    ],
    "label": "Color 3",
    "max": 1.0,
    "min": 0.0,
    "name": "color3",
    "offset": 16,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0,
     1.0,
     0.0,
     1.0
    ],
    "label": "Color 4",
    "max": 1.0,
    "min": 0.0,
    "name": "color4",
    "offset": 20,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Opacity",
    "max": 1.0,
    "min": 0.0,
    "name": "opacity",
    "offset": 24,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Four Points Gradient"
 },
 "hls_adjust": {
  "group": "Color",
  "hidden": false,
  "id": 5,
  "nparams": 10,
  "params": [
   {
    "default": [
     0.0
    ],
    "label": "Hue pivot",
    "max": 360.0,
    "min": 0.0,
    "name": "huePivot",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Hue scale",
    "max": 4.0,
    "min": -4.0,
    "name": "hueScale",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Hue shift",
    "max": 360.0,
    "min": -360.0,
    "name": "hueShift",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Lightness pivot",
    "max": 1.0,
    "min": 0.0,
    "name": "ligPivot",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Lightness scale",
    "max": 4.0,
    "min": 0.0,
    "name": "ligScale",
    "offset": 4,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Lightness shift",
    "max": 1.0,
    "min": -1.0,
    "name": "ligShift",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Saturation pivot",
    "max": 1.0,
    "min": 0.0,
    "name": "satPivot",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Saturation scale",
    "max": 4.0,
    "min": 0.0,
    "name": "satScale",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Saturation shift",
    "max": 1.0,
    "min": -1.0,
    "name": "satShift",
    "offset": 8,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Cylindrical",
    "max": 1.0,
    "min": 0.0,
    "name": "cylindrical",
    "offset": 9,
    "size": 1,
    "type": "bool"
   }
  ],
  "title": "HLS Adjust"
 },
 "hsv_adjust": {
  "group": "Color",
  "hidden": false,
  "id": 4,
  "nparams": 9,
  "params": [
   {
    "default": [
     0.0
    ],
    "label": "Hue pivot",
    "max": 360.0,
    "min": 0.0,
    "name": "huePivot",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Hue scale",
    "max": 4.0,
    "min": -4.0,
    "name": "hueScale",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Hue shift",
    "max": 360.0,
    "min": -360.0,
    "name": "hueShift",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Value pivot",
    "max": 1.0,
    "min": 0.0,
    "name": "valPivot",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Value scale",
    "max": 4.0,
    "min": 0.0,
    "name": "valScale",
    "offset": 4,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Value shift",
    "max": 1.0,
    "min": -1.0,
    "name": "valShift",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Saturation pivot",
    "max": 1.0,
    "min": 0.0,
    "name": "satPivot",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Saturation scale",
    "max": 4.0,
    "min": 0.0,
    "name": "satScale",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Saturation shift",
    "max": 1.0,
    "min": -1.0,
    "name": "satShift",
    "offset": 8,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "HSV Adjust"
 },
 "levels": {
  "group": "Color",
  "hidden": false,
  "id": 6,
  "nparams": 6,
  "params": [
   {
    "default": [
     0.0
    ],
    "label": "Input low",
    "max": 1.0,
    "min": 0.0,
    "name": "inMin",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Input high",
    "max": 1.0,
    "min": 0.0,
    "name": "inMax",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Gamma",
    "max": 10.0,
    "min": 0.1,
    "name": "gamma",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Output low",
    "max": 1.0,
    "min": 0.0,
    "name": "outMin",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Output high",
    "max": 1.0,
    "min": 0.0,
    "name": "outMax",
    "offset": 4,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Clamp",
    "max": 1.0,
    "min": 0.0,
    "name": "clampSw",
    "offset": 5,
    "size": 1,
    "type": "bool"
   }
  ],
  "title": "Levels"
 },
 "levels_rgb": {
  "group": "Color",
  "hidden": false,
  "id": 7,
  "nparams": 16,
  "params": [
   {
    "default": [
     0.0
    ],
    "label": "Red input low",
    "max": 1.0,
    "min": 0.0,
    "name": "redInMin",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Red input high",
    "max": 1.0,
    "min": 0.0,
    "name": "redInMax",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Red gamma",
    "max": 10.0,
    "min": 0.1,
    "name": "redGamma",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Red output low",
    "max": 1.0,
    "min": 0.0,
    "name": "redOutMin",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Red output high",
    "max": 1.0,
    "min": 0.0,
    "name": "redOutMax",
    "offset": 4,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Green input low",
    "max": 1.0,
    "min": 0.0,
    "name": "greenInMin",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Green input high",
    "max": 1.0,
    "min": 0.0,
    "name": "greenInMax",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Green gamma",
    "max": 10.0,
    "min": 0.1,
    "name": "greenGamma",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Green output low",
    "max": 1.0,
    "min": 0.0,
    "name": "greenOutMin",
    "offset": 8,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Green output high",
    "max": 1.0,
    "min": 0.0,
    "name": "greenOutMax",
    "offset": 9,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Blue input low",
    "max": 1.0,
    "min": 0.0,
    "name": "blueInMin",
    "offset": 10,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Blue input high",
    "max": 1.0,
    "min": 0.0,
    "name": "blueInMax",
    "offset": 11,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Blue gamma",
    "max": 10.0,
    "min": 0.1,
    "name": "blueGamma",
    "offset": 12,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Blue output low",
    "max": 1.0,
    "min": 0.0,
    "name": "blueOutMin",
    "offset": 13,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Blue output high",
    "max": 1.0,
    "min": 0.0,
    "name": "blueOutMax",
    "offset": 14,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Clamp",
    "max": 1.0,
    "min": 0.0,
    "name": "clampSw",
    "offset": 15,
    "size": 1,
    "type": "bool"
   }
  ],
  "title": "Levels (RGB)"
 },
 "lights": {
  "group": "Light",
  "hidden": false,
  "id": 14,
  "nparams": 32,
  "params": [
   {
    "default": [
     0.18,
     0.2,
     0.3,
     1.0
    ],
    "label": "Ambient",
    "max": 1.0,
    "min": 0.0,
    "name": "ambient",
    "offset": 0,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Falloff",
    "max": 2.0,
    "min": 0.0,
    "name": "falloff",
    "offset": 4,
    "options": [
     "Linear",
     "Smooth",
     "Quadratic"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.15
    ],
    "label": "Glow",
    "max": 1.0,
    "min": 0.0,
    "name": "glow",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 1 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l1x",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 1 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l1y",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.35
    ],
    "label": "Light 1 radius",
    "max": 2.0,
    "min": 0.0,
    "name": "l1r",
    "offset": 8,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Light 1 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l1k",
    "offset": 9,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.8,
     0.5,
     1.0
    ],
    "label": "Light 1 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l1c",
    "offset": 12,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.7
    ],
    "label": "Light 2 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l2x",
    "offset": 16,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 2 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l2y",
    "offset": 17,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 2 radius",
    "max": 2.0,
    "min": 0.0,
    "name": "l2r",
    "offset": 18,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 2 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l2k",
    "offset": 19,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4,
     0.7,
     1.0,
     1.0
    ],
    "label": "Light 2 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l2c",
    "offset": 20,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 3 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l3x",
    "offset": 24,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.8
    ],
    "label": "Light 3 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l3y",
    "offset": 25,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.25
    ],
    "label": "Light 3 radius",
    "max": 2.0,
    "min": 0.0,
    "name": "l3r",
    "offset": 26,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 3 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l3k",
    "offset": 27,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.4,
     0.6,
     1.0
    ],
    "label": "Light 3 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l3c",
    "offset": 28,
    "size": 4,
    "type": "color"
   }
  ],
  "title": "Point Lights"
 },
 "linear_gradient": {
  "group": "Gradient",
  "hidden": false,
  "id": 8,
  "nparams": 18,
  "params": [
   {
    "default": [
     0.5
    ],
    "label": "Center X",
    "max": 1.0,
    "min": 0.0,
    "name": "centerX",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Center Y",
    "max": 1.0,
    "min": 0.0,
    "name": "centerY",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Angle",
    "max": 360.0,
    "min": -360.0,
    "name": "angle",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     200.0
    ],
    "label": "Period",
    "max": 10000.0,
    "min": 1.0,
    "name": "period",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Wave amplitude",
    "max": 1000.0,
    "min": 0.0,
    "name": "waveAmp",
    "offset": 4,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Wave frequency",
    "max": 1.0,
    "min": 0.0,
    "name": "waveFreq",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Wave phase",
    "max": 6.3,
    "min": -6.3,
    "name": "wavePhase",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Offset",
    "max": 10000.0,
    "min": -10000.0,
    "name": "cycle",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0,
     0.0,
     0.0,
     1.0
    ],
    "label": "Color 1",
    "max": 1.0,
    "min": 0.0,
    "name": "color1",
    "offset": 8,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0,
     1.0,
     1.0,
     1.0
    ],
    "label": "Color 2",
    "max": 1.0,
    "min": 0.0,
    "name": "color2",
    "offset": 12,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.0
    ],
    "label": "Curve",
    "max": 3.0,
    "min": 0.0,
    "name": "curve",
    "offset": 16,
    "options": [
     "EaseInOut",
     "Linear",
     "EaseIn",
     "EaseOut"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     1.0
    ],
    "label": "Opacity",
    "max": 1.0,
    "min": 0.0,
    "name": "opacity",
    "offset": 17,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Linear Gradient"
 },
 "radial_gradient": {
  "group": "Gradient",
  "hidden": false,
  "id": 9,
  "nparams": 14,
  "params": [
   {
    "default": [
     0.5
    ],
    "label": "Center X",
    "max": 1.0,
    "min": 0.0,
    "name": "centerX",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Center Y",
    "max": 1.0,
    "min": 0.0,
    "name": "centerY",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     100.0
    ],
    "label": "Outer radius",
    "max": 10000.0,
    "min": 1.0,
    "name": "period",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Inner radius",
    "max": 10000.0,
    "min": 0.0,
    "name": "innerPeriod",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     1.0,
     1.0,
     1.0
    ],
    "label": "Color 1",
    "max": 1.0,
    "min": 0.0,
    "name": "color1",
    "offset": 4,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0,
     1.0,
     1.0,
     0.0
    ],
    "label": "Color 2",
    "max": 1.0,
    "min": 0.0,
    "name": "color2",
    "offset": 8,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Curve",
    "max": 3.0,
    "min": 0.0,
    "name": "curve",
    "offset": 12,
    "options": [
     "EaseInOut",
     "Linear",
     "EaseIn",
     "EaseOut"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     1.0
    ],
    "label": "Opacity",
    "max": 1.0,
    "min": 0.0,
    "name": "opacity",
    "offset": 13,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Radial Gradient"
 },
 "scene_lights": {
  "group": "Light",
  "hidden": true,
  "id": 16,
  "nparams": 104,
  "params": [
   {
    "default": [
     0.18,
     0.2,
     0.3,
     1.0
    ],
    "label": "Ambient",
    "max": 1.0,
    "min": 0.0,
    "name": "ambient",
    "offset": 0,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Falloff",
    "max": 2.0,
    "min": 0.0,
    "name": "falloff",
    "offset": 4,
    "options": [
     "Linear",
     "Smooth",
     "Quadratic"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.15
    ],
    "label": "Glow",
    "max": 1.0,
    "min": 0.0,
    "name": "glow",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Exposure",
    "max": 4.0,
    "min": 0.0,
    "name": "exposure",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Mix",
    "max": 1.0,
    "min": 0.0,
    "name": "mixAmt",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 1 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l0x",
    "offset": 8,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 1 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l0y",
    "offset": 9,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 1 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l0r",
    "offset": 10,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 1 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l0k",
    "offset": 11,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 1 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l0c",
    "offset": 12,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 1 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l0a",
    "offset": 16,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 1 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l0o",
    "offset": 17,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 1 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l0s",
    "offset": 18,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 1 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l0t",
    "offset": 19,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 2 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l1x",
    "offset": 20,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 2 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l1y",
    "offset": 21,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 2 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l1r",
    "offset": 22,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 2 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l1k",
    "offset": 23,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 2 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l1c",
    "offset": 24,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 2 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l1a",
    "offset": 28,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 2 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l1o",
    "offset": 29,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 2 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l1s",
    "offset": 30,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 2 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l1t",
    "offset": 31,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 3 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l2x",
    "offset": 32,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 3 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l2y",
    "offset": 33,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 3 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l2r",
    "offset": 34,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 3 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l2k",
    "offset": 35,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 3 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l2c",
    "offset": 36,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 3 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l2a",
    "offset": 40,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 3 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l2o",
    "offset": 41,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 3 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l2s",
    "offset": 42,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 3 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l2t",
    "offset": 43,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 4 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l3x",
    "offset": 44,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 4 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l3y",
    "offset": 45,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 4 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l3r",
    "offset": 46,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 4 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l3k",
    "offset": 47,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 4 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l3c",
    "offset": 48,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 4 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l3a",
    "offset": 52,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 4 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l3o",
    "offset": 53,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 4 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l3s",
    "offset": 54,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 4 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l3t",
    "offset": 55,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 5 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l4x",
    "offset": 56,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 5 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l4y",
    "offset": 57,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 5 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l4r",
    "offset": 58,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 5 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l4k",
    "offset": 59,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 5 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l4c",
    "offset": 60,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 5 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l4a",
    "offset": 64,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 5 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l4o",
    "offset": 65,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 5 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l4s",
    "offset": 66,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 5 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l4t",
    "offset": 67,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 6 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l5x",
    "offset": 68,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 6 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l5y",
    "offset": 69,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 6 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l5r",
    "offset": 70,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 6 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l5k",
    "offset": 71,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 6 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l5c",
    "offset": 72,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 6 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l5a",
    "offset": 76,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 6 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l5o",
    "offset": 77,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 6 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l5s",
    "offset": 78,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 6 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l5t",
    "offset": 79,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 7 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l6x",
    "offset": 80,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 7 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l6y",
    "offset": 81,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 7 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l6r",
    "offset": 82,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 7 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l6k",
    "offset": 83,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 7 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l6c",
    "offset": 84,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 7 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l6a",
    "offset": 88,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 7 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l6o",
    "offset": 89,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 7 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l6s",
    "offset": 90,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 7 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l6t",
    "offset": 91,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 8 X",
    "max": 1.0,
    "min": 0.0,
    "name": "l7x",
    "offset": 92,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Light 8 Y",
    "max": 1.0,
    "min": 0.0,
    "name": "l7y",
    "offset": 93,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.3
    ],
    "label": "Light 8 radius",
    "max": 3.0,
    "min": 0.0,
    "name": "l7r",
    "offset": 94,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 8 intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "l7k",
    "offset": 95,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     0.9,
     0.7,
     1.0
    ],
    "label": "Light 8 color",
    "max": 1.0,
    "min": 0.0,
    "name": "l7c",
    "offset": 96,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Light 8 direction",
    "max": 360.0,
    "min": -360.0,
    "name": "l7a",
    "offset": 100,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Light 8 cone",
    "max": 89.0,
    "min": 1.0,
    "name": "l7o",
    "offset": 101,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Light 8 softness",
    "max": 1.0,
    "min": 0.0,
    "name": "l7s",
    "offset": 102,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Light 8 kind",
    "max": 1.0,
    "min": 0.0,
    "name": "l7t",
    "offset": 103,
    "options": [
     "Point",
     "Spot"
    ],
    "size": 1,
    "type": "enum"
   }
  ],
  "title": "Scene Lights"
 },
 "spin_gradient": {
  "group": "Gradient",
  "hidden": false,
  "id": 12,
  "nparams": 14,
  "params": [
   {
    "default": [
     0.5
    ],
    "label": "Center X",
    "max": 1.0,
    "min": 0.0,
    "name": "centerX",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Center Y",
    "max": 1.0,
    "min": 0.0,
    "name": "centerY",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "Start angle",
    "max": 720.0,
    "min": -360.0,
    "name": "startAngle",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0
    ],
    "label": "End angle",
    "max": 720.0,
    "min": -360.0,
    "name": "endAngle",
    "offset": 3,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.0,
     0.0,
     0.0,
     1.0
    ],
    "label": "Color 1",
    "max": 1.0,
    "min": 0.0,
    "name": "color1",
    "offset": 4,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0,
     1.0,
     1.0,
     1.0
    ],
    "label": "Color 2",
    "max": 1.0,
    "min": 0.0,
    "name": "color2",
    "offset": 8,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Curve",
    "max": 3.0,
    "min": 0.0,
    "name": "curve",
    "offset": 12,
    "options": [
     "EaseInOut",
     "Linear",
     "EaseIn",
     "EaseOut"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     1.0
    ],
    "label": "Opacity",
    "max": 1.0,
    "min": 0.0,
    "name": "opacity",
    "offset": 13,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Spin Gradient"
 },
 "spot_light": {
  "group": "Light",
  "hidden": false,
  "id": 15,
  "nparams": 17,
  "params": [
   {
    "default": [
     0.12,
     0.13,
     0.2,
     1.0
    ],
    "label": "Ambient",
    "max": 1.0,
    "min": 0.0,
    "name": "ambient",
    "offset": 0,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.5
    ],
    "label": "X",
    "max": 1.0,
    "min": 0.0,
    "name": "x",
    "offset": 4,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.1
    ],
    "label": "Y",
    "max": 1.0,
    "min": 0.0,
    "name": "y",
    "offset": 5,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     -90.0
    ],
    "label": "Direction",
    "max": 360.0,
    "min": -360.0,
    "name": "angle",
    "offset": 6,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     30.0
    ],
    "label": "Cone half-angle",
    "max": 89.0,
    "min": 1.0,
    "name": "cone",
    "offset": 7,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.4
    ],
    "label": "Edge softness",
    "max": 1.0,
    "min": 0.0,
    "name": "softness",
    "offset": 8,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Reach",
    "max": 3.0,
    "min": 0.01,
    "name": "radius",
    "offset": 9,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.2
    ],
    "label": "Intensity",
    "max": 4.0,
    "min": 0.0,
    "name": "intensity",
    "offset": 10,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0
    ],
    "label": "Falloff",
    "max": 2.0,
    "min": 0.0,
    "name": "falloff",
    "offset": 11,
    "options": [
     "Linear",
     "Smooth",
     "Quadratic"
    ],
    "size": 1,
    "type": "enum"
   },
   {
    "default": [
     1.0,
     0.95,
     0.8,
     1.0
    ],
    "label": "Color",
    "max": 1.0,
    "min": 0.0,
    "name": "color",
    "offset": 12,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.1
    ],
    "label": "Glow",
    "max": 1.0,
    "min": 0.0,
    "name": "glow",
    "offset": 16,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Spot Light"
 },
 "square_gradient": {
  "group": "Gradient",
  "hidden": false,
  "id": 10,
  "nparams": 13,
  "params": [
   {
    "default": [
     0.5
    ],
    "label": "Center X",
    "max": 1.0,
    "min": 0.0,
    "name": "centerX",
    "offset": 0,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     0.5
    ],
    "label": "Center Y",
    "max": 1.0,
    "min": 0.0,
    "name": "centerY",
    "offset": 1,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     200.0
    ],
    "label": "Size",
    "max": 10000.0,
    "min": 1.0,
    "name": "size",
    "offset": 2,
    "size": 1,
    "type": "float"
   },
   {
    "default": [
     1.0,
     1.0,
     1.0,
     1.0
    ],
    "label": "Color 1",
    "max": 1.0,
    "min": 0.0,
    "name": "color1",
    "offset": 4,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.0,
     0.0,
     0.0,
     1.0
    ],
    "label": "Color 2",
    "max": 1.0,
    "min": 0.0,
    "name": "color2",
    "offset": 8,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     1.0
    ],
    "label": "Opacity",
    "max": 1.0,
    "min": 0.0,
    "name": "opacity",
    "offset": 12,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Square Gradient"
 },
 "tint": {
  "group": "Color",
  "hidden": false,
  "id": 2,
  "nparams": 5,
  "params": [
   {
    "default": [
     1.0,
     0.5,
     0.1,
     1.0
    ],
    "label": "Colour",
    "max": 1.0,
    "min": 0.0,
    "name": "color",
    "offset": 0,
    "size": 4,
    "type": "color"
   },
   {
    "default": [
     0.5
    ],
    "label": "Amount",
    "max": 1.0,
    "min": 0.0,
    "name": "amount",
    "offset": 4,
    "size": 1,
    "type": "float"
   }
  ],
  "title": "Tint"
 }
}
''')

BY_ID = {e["id"]: n for n, e in EFFECTS.items()}
