#!/usr/bin/env python3
"""engine_so.py -- build libstride2d.so: the Stride2D engine as C, in one shared library a Python (ctypes) host can load.

    python3 tools/engine_so.py [-o /tmp/libstride2d.so] [--cc CC]
    (or:  python3 build.py so)

What goes in it:

  1. src/engine/Engine.cs, a flat handle-based facade over the runtime (ints and floats only), translated to C together with the runtime by CCSharp (the only
     step that needs .NET: the translator is built on Roslyn; the library that comes out has none);
  2. a shim generated from Engine.cs's `public static` signatures: each becomes an exported `p2d_<snake_case>` function (NewNode -> p2d_new_node), so the
     C# and the exports cannot drift apart;
  3. the renderer, src/native/gfx2d, whose gfx_* functions are exported as they are: the window and its events, textures, triangles, clip, fonts;
  4. Box2D and its shim, statically.

The library needs only libdl, libm and libc at run time (the renderer loads EGL, GLES and X11 with dlopen, and falls back to its CPU rasteriser).
Build needs what `python3 build.py deps`, `native` and `ccsharp` set up.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import gfx_build      # noqa: E402
import player_build   # noqa: E402

C_TYPES = {"int": "int", "float": "float", "void": "void"}


def snake(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def parse_api(cs_path):
    """The `public static` functions of the Engine class: [(ret, Name, [(type, name), ...])]. Only int, float and void are allowed: this is what a ctypes
    host can call without building anything, so a signature outside that is an error here, not a surprise later."""
    with open(cs_path, encoding="utf-8") as f:
        text = re.sub(r"//[^\n]*", "", f.read())
    api = []
    for m in re.finditer(r"public\s+static\s+(\w+)\s+(\w+)\s*\(([^)]*)\)", text):
        ret, name, params = m.group(1), m.group(2), m.group(3).strip()
        if name == "Main":
            continue
        plist = []
        for p in [x.strip() for x in params.split(",") if x.strip()]:
            parts = p.split()
            if len(parts) != 2 or parts[0] not in C_TYPES:
                sys.exit("engine_so: Engine.%s: parameter '%s' is not 'int x' or 'float x' (the exported API is ints and floats only)" % (name, p))
            plist.append((parts[0], parts[1]))
        if ret not in C_TYPES:
            sys.exit("engine_so: Engine.%s returns %s: only int, float and void are exported" % (name, ret))
        api.append((ret, name, plist))
    if not api:
        sys.exit("engine_so: no public static functions found in %s" % cs_path)
    return api


def exports_c(api):
    lines = ["/* engine_exports.c: GENERATED by tools/engine_so.py from src/engine/Engine.cs. Do not edit; change Engine.cs and rebuild. */",
             "#define main stride2d_discarded_main /* the translated entry point is not wanted in a library */",
             '#include "player.c"',
             "#undef main",
             "#define P2D_EXPORT __attribute__((visibility(\"default\")))",
             ""]
    for ret, name, plist in api:
        proto = ", ".join("%s %s" % (C_TYPES[t], n) for t, n in plist) or "void"
        call = "Engine_%s(%s)" % (name, ", ".join(n for _, n in plist))
        body = ("return " + call + ";") if ret != "void" else (call + ";")
        lines.append("P2D_EXPORT %s p2d_%s(%s) { %s }" % (C_TYPES[ret], snake(name), proto, body))
    return "\n".join(lines) + "\n"


def header_h(api):
    lines = ["/* libstride2d.h: the exported engine API (generated with the library from src/engine/Engine.cs). The renderer's gfx_* functions are exported too: src/native/gfx2d/gfx2d.h. */",
             "#ifndef LIBSTRIDE2D_H", "#define LIBSTRIDE2D_H", ""]
    for ret, name, plist in api:
        proto = ", ".join("%s %s" % (C_TYPES[t], n) for t, n in plist) or "void"
        lines.append("%s p2d_%s(%s);" % (C_TYPES[ret], snake(name), proto))
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        print("   $ " + " ".join(cmd))
        print((r.stdout + r.stderr)[-2500:])
        sys.exit("engine_so: failed (%d)" % r.returncode)
    return r


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", default="/tmp/libstride2d.so", help="the library to write (default /tmp/libstride2d.so); libstride2d.h is written beside it")
    ap.add_argument("--cc", default=os.environ.get("CC") or "cc")
    a = ap.parse_args()

    cs = os.path.join(ROOT, "src", "engine", "Engine.cs")
    api = parse_api(cs)
    work = os.path.join(ROOT, "build", "engine")
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(work)
    for need in (player_build.SHIM_A, player_build.BOX2D_LIB):
        if not os.path.exists(need):
            sys.exit("engine_so: %s is missing (python3 build.py native)" % need)

    print("== translating src/engine/Engine.cs with the runtime (%d exported functions)" % len(api))
    c_file, diags, raw = player_build.translate([cs], work, "Engine")
    if c_file is None:
        print("\n".join(diags) if diags else raw[-2000:])
        sys.exit("engine_so: the translator refused Engine.cs (see above)")
    print("   %s  (%d lines of C)" % (os.path.relpath(c_file, ROOT), sum(1 for _ in open(c_file))))

    shutil.copy2(c_file, os.path.join(work, "player.c"))
    shutil.copy2(player_build.SHIM_H, work)
    shutil.copy2(player_build.GFX_H, work)
    with open(os.path.join(work, "engine_exports.c"), "w", newline="\n") as f:
        f.write(exports_c(api))

    print("== the renderer")
    gfx = gfx_build.build(quiet=True)
    print("== linking %s" % a.out)
    out = os.path.abspath(a.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    cmd = ([a.cc, "-shared", "-fPIC", "-O2", "-ffp-contract=off", "-w", "-I", work, "-o", out, os.path.join(work, "engine_exports.c"),
            "-Wl,--whole-archive", gfx["static"], "-Wl,--no-whole-archive", player_build.SHIM_A, player_build.BOX2D_LIB, "-ldl", "-lm"])
    run(cmd, cwd=work)
    with open(os.path.join(os.path.dirname(out), "libstride2d.h"), "w", newline="\n") as f:
        f.write(header_h(api))
    print("   built %s  (%d KiB)" % (out, os.path.getsize(out) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
