#!/usr/bin/env python3
"""engine_so.py -- build libstride2d.so: the Stride2D engine as C, in one shared library a Python (ctypes) host can load.

    python3 tools/engine_so.py [-o /tmp/libstride2d.so] [--cc CC]
    (or:  python3 build.py so)

What goes in it:

  1. src/engine/Engine.cs, a flat handle-based facade over the runtime (ints and floats only), translated to C together with the runtime by CCSharp (the only
     step that needs .NET: the translator is built on Roslyn; the library that comes out has none);
  2. a shim generated from Engine.cs's `public static` signatures: each becomes an exported `p2d_<snake_case>` function (NewNode -> p2d_new_node), so the
     C# and the exports cannot drift apart;
  3. the renderer, src/native/gfx2d, whose gfx_* functions are exported as they are: the window and its events, textures, triangles, clip, fonts;
  4. Box2D and its shim, statically.

The library needs only libdl, libm and libc at run time (the renderer loads EGL, GLES and X11 with dlopen, and falls back to its CPU rasteriser).
Build needs what `python3 build.py deps`, `native` and `ccsharp` set up.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import gfx_build      # noqa: E402
import player_build   # noqa: E402
import gen_scripts    # noqa: E402

C_TYPES = {"int": "int", "float": "float", "void": "void"}


def snake(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def parse_api(cs_path):
    """The `public static` functions of the Engine class: [(ret, Name, [(type, name), ...])]. Only int, float and void are allowed: this is what a ctypes
    host can call without building anything, so a signature outside that is an error here, not a surprise later."""
    with open(cs_path, encoding="utf-8") as f:
        text = re.sub(r"//[^\n]*", "", f.read())
    api = []
    for m in re.finditer(r"public\s+static\s+(\w+)\s+(\w+)\s*\(([^)]*)\)", text):
        ret, name, params = m.group(1), m.group(2), m.group(3).strip()
        if name == "Main":
            continue
        plist = []
        for p in [x.strip() for x in params.split(",") if x.strip()]:
            parts = p.split()
            if len(parts) != 2 or parts[0] not in C_TYPES:
                sys.exit("engine_so: Engine.%s: parameter '%s' is not 'int x' or 'float x' (the exported API is ints and floats only)" % (name, p))
            plist.append((parts[0], parts[1]))
        if ret not in C_TYPES:
            sys.exit("engine_so: Engine.%s returns %s: only int, float and void are exported" % (name, ret))
        api.append((ret, name, plist))
    if not api:
        sys.exit("engine_so: no public static functions found in %s" % cs_path)
    return api


def exports_c(api):
    lines = ["/* engine_exports.c: GENERATED by tools/engine_so.py from src/engine/Engine.cs. Do not edit; change Engine.cs and rebuild. */",
             "#define main stride2d_discarded_main /* the translated entry point is not wanted in a library */",
             '#include "player.c"',
             "#undef main",
             "#define P2D_EXPORT __attribute__((visibility(\"default\")))",
             ""]
    for ret, name, plist in api:
        proto = ", ".join("%s %s" % (C_TYPES[t], n) for t, n in plist) or "void"
        call = "Engine_%s(%s)" % (name, ", ".join(n for _, n in plist))
        body = ("return " + call + ";") if ret != "void" else (call + ";")
        lines.append("P2D_EXPORT %s p2d_%s(%s) { %s }" % (C_TYPES[ret], snake(name), proto, body))
    return "\n".join(lines) + "\n"


def header_h(api):
    lines = ["/* libstride2d.h: the exported engine API (generated with the library from src/engine/Engine.cs). The renderer's gfx_* functions are exported too: src/native/gfx2d/gfx2d.h. */",
             "#ifndef LIBSTRIDE2D_H", "#define LIBSTRIDE2D_H", ""]
    for ret, name, plist in api:
        proto = ", ".join("%s %s" % (C_TYPES[t], n) for t, n in plist) or "void"
        lines.append("%s p2d_%s(%s);" % (C_TYPES[ret], snake(name), proto))
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def user_scripts(folder):
    """The project's scripts: every .cs file of `folder`, and the [Script] classes in them as [(class name, capacity, file)] in file order. A mistake the script
    generator can name (no [MaxInstances], no `public Component Self;`, a callback that would never be called) is a diagnostic in the compiler's own format."""
    files = sorted(os.path.join(folder, f) for f in os.listdir(folder) if f.endswith(".cs"))
    found = []
    for path in files:
        try:
            _ns, scripts = gen_scripts.scan_file(path)
        except gen_scripts.GenError as e:
            msg = str(e)
            m = re.match(r"(.*?):(\d+):\s*(.*)", msg, re.S)
            line, text = (int(m.group(2)), m.group(3)) if m else (1, msg)
            sys.exit("%s(%d,1): error GEN0001: %s" % (os.path.basename(path), line, text.replace("\n", " ")))
        for sc in scripts:
            found.append((sc["name"], sc["capacity"], path))
    names = [n for n, _, _ in found]
    for n in names:
        if names.count(n) > 1:
            sys.exit("error GEN0002: two scripts are called %s" % n)
    return files, found


def script_table_cs(found):
    """ScriptTable.g.cs: Engine.AttachScript(node, number) -> the generated factory of that script. The number is the script's place in the manifest."""
    L = ["// <auto-generated> by tools/engine_so.py: the project's scripts by number. </auto-generated>", "namespace Stride2D;", "",
         "internal static class ScriptTable", "{", "    public static int Count() { return %d; }" % len(found), "", "    public static int Add(Node node, int id)", "    {"]
    for i, (name, _cap, _p) in enumerate(found):
        L += ["        if (id == %d)" % i, "        {", "            %s s = Scripts.Add%s(node);" % (name, name), "            if (s != null) return 1;", "            return 0;", "        }"]
    L += ["        return 0;", "    }", "}", ""]
    return "\n".join(L)


def run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        print("   $ " + " ".join(cmd))
        print((r.stdout + r.stderr)[-2500:])
        sys.exit("engine_so: failed (%d)" % r.returncode)
    return r


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("-o", "--out", default="/tmp/libstride2d.so", help="the library to write (default /tmp/libstride2d.so); libstride2d.h is written beside it")
    ap.add_argument("--cc", default=os.environ.get("CC") or "cc")
    ap.add_argument("--scripts", metavar="DIR", help="a folder of .cs files whose [Script] classes are built into the library (Engine.AttachScript attaches them by number); "
                    "writes OUT.scripts.json beside the library: the numbers. Errors are printed as File.cs(line,col): error ...")
    ap.add_argument("--work", metavar="DIR", help="the work folder (default build/engine); the editor's Build uses its own, so the engine's is left alone")
    a = ap.parse_args()

    cs = os.path.join(ROOT, "src", "engine", "Engine.cs")
    api = parse_api(cs)
    work = os.path.abspath(a.work) if a.work else os.path.join(ROOT, "build", "engine")
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(work)
    script_files, found = user_scripts(os.path.abspath(a.scripts)) if a.scripts else ([], [])
    table = os.path.join(work, "ScriptTable.g.cs")
    with open(table, "w", newline="\n") as f:
        f.write(script_table_cs(found))
    for need in (player_build.SHIM_A, player_build.BOX2D_LIB):
        if not os.path.exists(need):
            sys.exit("engine_so: %s is missing (python3 build.py native)" % need)

    print("== translating src/engine/Engine.cs with the runtime (%d exported functions)" % len(api))
    c_file, diags, raw = player_build.translate([cs, os.path.join(ROOT, "src", "engine", "Input2D.cs"), table] + script_files, work, "Engine")
    if c_file is None:
        print("\n".join(diags) if diags else raw[-2000:])
        sys.exit("engine_so: the translator refused Engine.cs (see above)")
    print("   %s  (%d lines of C)" % (os.path.relpath(c_file, ROOT), sum(1 for _ in open(c_file))))

    shutil.copy2(c_file, os.path.join(work, "player.c"))
    shutil.copy2(player_build.SHIM_H, work)
    shutil.copy2(player_build.GFX_H, work)
    with open(os.path.join(work, "engine_exports.c"), "w", newline="\n") as f:
        f.write(exports_c(api))

    print("== the renderer")
    gfx = gfx_build.build(quiet=True)
    print("== linking %s" % a.out)
    out = os.path.abspath(a.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    cmd = ([a.cc, "-shared", "-fPIC", "-O2", "-ffp-contract=off", "-w", "-I", work, "-o", out, os.path.join(work, "engine_exports.c"),
            "-Wl,--whole-archive", gfx["static"], "-Wl,--no-whole-archive", player_build.SHIM_A, player_build.BOX2D_LIB, "-ldl", "-lm"])
    run(cmd, cwd=work)
    with open(os.path.join(os.path.dirname(out), "libstride2d.h"), "w", newline="\n") as f:
        f.write(header_h(api))
    with open(out + ".scripts.json", "w", newline="\n") as f:
        json.dump([{"id": i, "name": n, "capacity": c, "file": os.path.basename(p)} for i, (n, c, p) in enumerate(found)], f, indent=1)
    print("   built %s  (%d KiB)" % (out, os.path.getsize(out) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
