#!/usr/bin/env python3
"""
font_bake.py - bakes a TrueType font into the bitmap fonts of Gfx2D (src/native/gfx2d/gfx2d_font_data.c).

  python3 tools/font_bake.py [--font FILE.ttf] [--sizes 14,20,28,40] [--out FILE.c]

Each size becomes one alpha atlas (coverage, 8 bits) and a table of glyphs: for the characters U+0020..U+007E and U+00A0..U+00FF, where the glyph is in the atlas, its size
in pixels, where its box lies relative to the pen (at the baseline), and how far the pen moves. Needs Pillow (with FreeType). The atlases are stored run-length coded (a zero byte,
then how many zeros) so the generated file stays small; gfx2d_font.c decodes them. Kerning is not baked.

The default font is DejaVu Sans, whose license (Bitstream Vera, free to use, embed and redistribute) is in src/native/gfx2d/FONT-LICENSE.txt.
"""
import argparse, os, sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("font_bake: needs Pillow (pip install pillow)")

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CODES = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100))
PAD = 2        # empty pixels around each glyph, so bilinear filtering never reads a neighbour


def bake(path, size):
    font = ImageFont.truetype(path, size, layout_engine=ImageFont.Layout.BASIC)
    ascent, descent = font.getmetrics()
    glyphs = []
    for c in CODES:
        ch = chr(c)
        l, t, r, b = font.getbbox(ch, anchor="ls")           # relative to the pen at the baseline, y down
        w, h = max(r - l, 0), max(b - t, 0)
        glyphs.append(dict(code=c, w=w, h=h, bx=l, by=-t, adv=font.getlength(ch), l=l, t=t))
    # shelf packing in code order, into whichever power-of-two width gives the smallest picture (the height is not rounded: textures need not be a power of two)
    def pack(width):
        x = y = row = 0
        pos = []
        for g in glyphs:
            if x + g["w"] + PAD > width: x, y, row = 0, y + row, 0
            pos.append((x + PAD // 2, y + PAD // 2))
            x += g["w"] + PAD
            row = max(row, g["h"] + PAD)
        return pos, y + row
    best = min(((w, pack(w)) for w in (64, 128, 256, 512) if w >= max(g["w"] for g in glyphs) + PAD), key=lambda t: t[0] * t[1][1])
    width, (pos, height) = best
    for g, (px, py) in zip(glyphs, pos): g["x"], g["y"] = px, py
    h2 = height
    atlas = Image.new("L", (width, h2), 0)
    d = ImageDraw.Draw(atlas)
    for g in glyphs:
        if g["w"] and g["h"]:
            d.text((g["x"] - g["l"], g["y"] - g["t"]), chr(g["code"]), font=font, fill=255, anchor="ls")
    return dict(size=size, ascent=ascent, descent=descent, width=width, height=h2, glyphs=glyphs, pixels=atlas.tobytes())


def rle(data):
    out = bytearray()
    i = 0
    while i < len(data):
        if data[i] == 0:
            j = i
            while j < len(data) and data[j] == 0 and j - i < 255: j += 1
            out += bytes([0, j - i]); i = j
        else:
            out.append(data[i]); i += 1
    return bytes(out)


def emit(fonts, path, font_path):
    L = ["// GENERATED by tools/font_bake.py from %s: do not edit. The font's license is FONT-LICENSE.txt." % os.path.basename(font_path),
         "// Per size: the atlas (run-length coded: a 0 byte then a count of zeros; any other byte is itself) and one row per glyph.",
         '#include "gfx2d_font.h"', ""]
    for k, f in enumerate(fonts):
        enc = rle(f["pixels"])
        L.append("static const unsigned char atlas_%d[%d] = {" % (k, len(enc)))
        for i in range(0, len(enc), 24): L.append("\t" + ",".join(str(b) for b in enc[i:i + 24]) + ",")
        L.append("};")
        L.append("static const GfxGlyphRow glyphs_%d[%d] = {" % (k, len(f["glyphs"])))
        for g in f["glyphs"]:
            L.append("\t{ %d, %d, %d, %d, %d, %d, %d, %.4ff }," % (g["code"], g["x"], g["y"], g["w"], g["h"], g["bx"], g["by"], g["adv"]))
        L.append("};")
        L.append("")
    L.append("const GfxBakedFont gfx_baked_fonts[GFX_BAKED_FONTS] = {")
    for k, f in enumerate(fonts):
        L.append("\t{ %d, %d, %d, %d, %d, atlas_%d, %d, glyphs_%d, %d }," % (f["size"], f["ascent"], f["descent"], f["width"], f["height"], k,
                                                                           len(rle(f["pixels"])), k, len(f["glyphs"])))
    L.append("};")
    open(path, "w", newline="\n").write("\n".join(L) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--font", default="/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
    ap.add_argument("--sizes", default="14,20,28,40")
    ap.add_argument("--out", default=os.path.join(ROOT, "src", "native", "gfx2d", "gfx2d_font_data.c"))
    a = ap.parse_args()
    sizes = [int(s) for s in a.sizes.split(",")]
    fonts = [bake(a.font, s) for s in sizes]
    emit(fonts, a.out, a.font)
    for f in fonts:
        print("size %2d: atlas %dx%d, %d glyphs, ascent %d descent %d" % (f["size"], f["width"], f["height"], len(f["glyphs"]), f["ascent"], f["descent"]))
    print("wrote", a.out, "(%d KiB)" % (os.path.getsize(a.out) // 1024))


if __name__ == "__main__":
    main()
