#!/usr/bin/env python3
"""script_native.py -- building the scripts that are not C#: Crust lowers them to C, the engine library links the C.

A script of another language reaches the C# engine through a thin proxy, so that the scene's call stream (Scripts.g.cs, tools/ccsharp/gen_scripts.py) needs no change:

    Name.cpp / .rs / .py   the script, as the person wrote it (plus glue appended to a COPY, so that an error's file and line are the script's own)
    Name.proxy.cs          a generated C# script `Name` with the same [MaxInstances(N)] and one method per callback the script has; each calls into the native glue with the
                           script's pool slot and its node's handle (an int, the one the engine's p2d_* functions take)
    P2DNative.c.cs         the bindings (C flavor, tools/ccsharp/gen_pb2.py's convention) that name the glue functions for the C# above
    p2d_native.h           the glue's prototypes, which the translated C includes
    stride2d.h                what a script #includes: the engine's calls under their C# names (SetPos, NodeX ...), from src/engine/Engine.cs

The glue keeps the script's instances in a static array of its capacity, indexed by the pool slot the C# side gives (a recycled slot is reset to zero), sets `node` before each
call, and calls the callback. Collision and trigger callbacks take the other node's handle (`int other`); a collision's point, normal and impulse are read with HitX() ... while
the callback runs.

The functions of one language (build_cpp, ...) return the object file that is linked into the library, or raise Failed with the front end's own output (the editor's
problems list reads it: scriptbuild.parse_diagnostics).
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import script_langs   # noqa: E402

# the engine functions a script is not given (the host's: the process, the frame, the input the host feeds, the scripts' own table)
HOST_ONLY = {"Version", "Init", "Shutdown", "Camera", "Clear", "ScriptCount", "SetKey", "SetMouse", "ClearInput", "Step", "Draw"}
CTYPES = {"int": "int", "float": "float", "void": "void"}

# the callbacks that take the other node's handle
WITH_OTHER = ["OnCollisionBegin2D", "OnCollisionEnd2D", "OnTriggerEnter2D", "OnTriggerStay2D", "OnTriggerExit2D"]
HIT = ["OnCollisionBegin2D", "OnCollisionEnd2D"]


class Failed(Exception):
    """A front end or the C compiler refused a script: .args[0] is what it said."""


def crust_home():
    return os.environ.get("CRUST_HOME") or os.path.join(os.path.dirname(ROOT), "crust")


def _snake(name):
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name).lower()


def id_name(script):
    """The constant a script's number is under, for the scripts that attach it to nodes they make: SCRIPT_ + the class name in capitals (Bullet: SCRIPT_BULLET, ArrowShooter: SCRIPT_ARROW_SHOOTER)."""
    return "SCRIPT_" + _snake(script).upper()


# ---- what every language needs

def engine_header(api, ids=None):
    """stride2d.h: the engine's script-facing functions, as `static inline` C functions under the C# names."""
    L = ["/* stride2d.h: GENERATED by tools/script_native.py from src/engine/Engine.cs. What a C++ script includes: the engine's calls under their C# names. */",
         "#ifndef PROWL_H", "#define PROWL_H", "", "#define STRIDE_SCRIPT(n)", ""]
    L += ["#define %s %d" % (id_name(n), i) for n, i in sorted((ids or {}).items(), key=lambda kv: kv[1])]
    L += ["", "extern \"C\" {"]
    wrappers = []
    for ret, name, plist in api:
        if name in HOST_ONLY:
            continue
        proto = ", ".join("%s %s" % (CTYPES[t], n) for t, n in plist) or "void"
        L.append("%s p2d_%s(%s);" % (CTYPES[ret], _snake(name), proto))
        call = "p2d_%s(%s)" % (_snake(name), ", ".join(n for _, n in plist))
        wrappers.append("static inline %s %s(%s) { %s }" % (CTYPES[ret], name, proto, ("return " + call + ";") if ret != "void" else (call + ";")))
    L += ["}", ""] + wrappers + ["",
          "/* a collision's point, normal and impulse: valid while OnCollisionBegin2D / OnCollisionEnd2D runs */",
          "static float p2d_hit[5];",
          "static inline float HitX() { return p2d_hit[0]; }", "static inline float HitY() { return p2d_hit[1]; }",
          "static inline float HitNX() { return p2d_hit[2]; }", "static inline float HitNY() { return p2d_hit[3]; }",
          "static inline float HitImpulse() { return p2d_hit[4]; }", "", "#endif", ""]
    return "\n".join(L)


def _params(cb):
    """The glue function's parameters after (slot, node): (C type, name) pairs."""
    if cb in HIT:
        return [("int", "other"), ("float", "x"), ("float", "y"), ("float", "nx"), ("float", "ny"), ("float", "impulse")]
    if cb in WITH_OTHER:
        return [("int", "other")]
    return []


def glue_prototypes(scripts):
    """p2d_native.h: the prototypes of every glue function (C names: p2dn_Script_Callback)."""
    L = ["/* p2d_native.h: GENERATED by tools/script_native.py: the glue of the scripts that are not C#. */", "#ifndef P2D_NATIVE_H", "#define P2D_NATIVE_H", ""]
    for s in scripts:
        L.append("void p2dn_%s_Reset(int slot);" % s["name"])
        for cb in s["callbacks"]:
            L.append("void p2dn_%s_%s(%s);" % (s["name"], cb, ", ".join(["int slot", "int node"] + ["%s %s" % p for p in _params(cb)])))
    return "\n".join(L + ["", "#endif", ""])


def bindings_cs(scripts):
    """The C-flavor bindings of the glue (the file goes in the translator's --bindings folder)."""
    L = ["// <auto-generated> by tools/script_native.py: names the glue of the scripts that are not C#. It holds no code. </auto-generated>", "",
         "using System.Collections.Generic;", "", "namespace Stride2D.Native.Scripts", "{"]
    for s in scripts:
        L += ["  [Crust.CppInclude(\"\\\"p2d_native.h\\\"\")]", "  public static class P2DNative_%s" % s["name"], "  {"]
        L.append("    [Crust.Cpp(\"p2dn_%s_Reset({0})\")] public static extern void Reset(int slot);" % s["name"])
        for cb in s["callbacks"]:
            ps = ["int slot", "int node"] + ["%s %s" % p for p in _params(cb)]
            L.append("    [Crust.Cpp(\"p2dn_%s_%s(%s)\")] public static extern void %s(%s);" % (s["name"], cb, ", ".join("{%d}" % i for i in range(len(ps))), cb, ", ".join(ps)))
        L += ["  }", ""]
    L.append("}")
    return "\n".join(L) + "\n"


def proxy_cs(s):
    """The C# script that stands for a native one: same name and capacity, a method per callback, each calling the glue."""
    n = s["name"]
    L = ["// <auto-generated> by tools/script_native.py: the C# face of the %s script %s (%s). </auto-generated>" % (script_langs.NAMES[s["language"]], n, os.path.basename(s["where"].rsplit(":", 1)[0])),
         "using Stride2D;", "using Stride2D.Native.Scripts;", "", "[Script, MaxInstances(%d)]" % s["capacity"], "class %s" % n, "{", "    public Component Self;", "",
         "    public void Reset() { P2DNative_%s.Reset(Self.Slot); }" % n, ""]
    for cb in s["callbacks"]:
        if cb in HIT:
            L += ["    public void %s(Collision2D hit)" % cb, "    {", "        int other = -1;", "        if (hit.Other != null) other = hit.Other.Self.Node.Index;",
                  "        P2DNative_%s.%s(Self.Slot, Self.Node.Index, other, hit.X, hit.Y, hit.NX, hit.NY, hit.Impulse);" % (n, cb), "    }"]
        elif cb in WITH_OTHER:
            L += ["    public void %s(Collider2D other)" % cb, "    {", "        int o = -1;", "        if (other != null) o = other.Self.Node.Index;",
                  "        P2DNative_%s.%s(Self.Slot, Self.Node.Index, o);" % (n, cb), "    }"]
        else:
            L.append("    public void %s() { P2DNative_%s.%s(Self.Slot, Self.Node.Index); }" % (cb, n, cb))
    L += ["}", ""]
    return "\n".join(L)


# ---- the glue, in C (a .rs file and a .py file are lowered to C, and C passes through the front ends untouched; C++ is lowered by cpprust, which takes this too)

def c_glue(s, call, init=None):
    """The glue appended to a script: the pool, and a C function per callback. `call(callback, instance, args)` is how the language calls the callback on `instance`;
    `init`, if given, is the C function that sets up a new instance (RPython's __init__), run before the instance's first callback and again after a reset."""
    n, cap = s["name"], s["capacity"]
    L = ["", "/* ---- glue (tools/script_native.py) ---- */", "static %s p2d_pool_%s[%d];" % (n, n, cap), "static %s p2d_zero_%s;" % (n, n)]
    if init:
        L.append("static int p2d_live_%s[%d];" % (n, cap))
    L.append("void p2dn_%s_Reset(int slot) { p2d_pool_%s[slot] = p2d_zero_%s;%s }" % (n, n, n, (" p2d_live_%s[slot] = 0;" % n) if init else ""))
    for cb in s["callbacks"]:
        sig = ", ".join(["int slot", "int node"] + ["%s %s" % p for p in _params(cb)])
        body = []
        if init:
            body.append("if (!p2d_live_%s[slot]) { %s(&p2d_pool_%s[slot]); p2d_live_%s[slot] = 1; }" % (n, init, n, n))
        body.append("p2d_pool_%s[slot].node = node;" % n)
        if cb in HIT:
            body += ["p2d_hit[%d] = %s;" % (i, name) for i, name in enumerate(["x", "y", "nx", "ny", "impulse"])]
        body.append(call(cb, "p2d_pool_%s[slot]" % n, ["other"] if cb in WITH_OTHER else []) + ";")
        L.append("void p2dn_%s_%s(%s) { %s }" % (n, cb, sig, " ".join(body)))
    return "\n".join(L) + "\n"


def glue_names(s):
    return ["p2dn_%s_Reset" % s["name"]] + ["p2dn_%s_%s" % (s["name"], cb) for cb in s["callbacks"]]


def _run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    return r.returncode, r.stdout + r.stderr


def _compile(s, c_path, work, cc, flags=()):
    """gcc on the C a front end wrote: an object whose only global symbols are the script's glue (several scripts' objects are linked into one library, and each front end's
    helpers and the engine wrappers are named alike in each of them), so the rest are made local."""
    obj = c_path[:-2] + ".o"
    code, out = _run([cc, "-c", "-fPIC", "-O2", "-ffp-contract=off", "-w", "-I", work] + list(flags) + ["-o", obj, c_path])
    if code != 0:
        raise Failed(out.strip())
    keep = c_path[:-2] + ".keep"
    with open(keep, "w") as f:
        f.write("\n".join(glue_names(s)) + "\n")
    code, out = _run(["objcopy", "--keep-global-symbols=" + keep, obj])
    if code != 0:
        raise Failed("objcopy: " + out.strip())
    return obj


def _copy_with(src_path, native_dir, tail):
    """The script copied into `native_dir` with `tail` after it (so that the lines of an error are the script's own)."""
    path = os.path.join(native_dir, os.path.basename(src_path))
    with open(src_path, encoding="utf-8") as f:
        text = f.read()
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text.rstrip("\n") + "\n" + tail)
    return path


# ---- C++

def build_cpp(s, src_path, native_dir, work, cc, api=None, ids=None):
    """Lowers one C++ script with cpprust and compiles the C: returns the object file. `native_dir` holds stride2d.h; the script file is copied there with the glue after it."""
    path = _copy_with(src_path, native_dir, c_glue(s, lambda cb, inst, args: "%s.%s(%s)" % (inst, cb, ", ".join(args))))
    c_path = path[:-len(".cpp")] + ".c"
    code, out = _run([sys.executable, os.path.join(crust_home(), "tools", "cpprust.py"), path, "-o", c_path, "--incdir", native_dir, "--basedir", native_dir])
    if code != 0 or not os.path.exists(c_path):
        raise Failed(out.strip() or "cpprust failed")
    return _compile(s, c_path, work, cc)


# ---- Rust

def rust_prelude(api, ids=None):
    """The engine's calls for a Rust script (snake_case: set_pos, node_x ...): C prototypes of the p2d_* functions and Rust wrappers over them, appended to the script."""
    L = ["", "/* ---- the engine (tools/script_native.py) ---- */", "static float p2d_hit[5];"]
    L += ["const %s: i32 = %d;" % (id_name(n), i) for n, i in sorted((ids or {}).items(), key=lambda kv: kv[1])]
    rust = {"int": "i32", "float": "f32", "void": None}
    for ret, name, plist in api:
        if name in HOST_ONLY:
            continue
        L.append("%s p2d_%s(%s);" % (CTYPES[ret], _snake(name), ", ".join("%s %s" % (CTYPES[t], n) for t, n in plist) or "void"))
    for ret, name, plist in api:
        if name in HOST_ONLY:
            continue
        sig = ", ".join("%s: %s" % (n, rust[t]) for t, n in plist)
        call = "p2d_%s(%s)" % (_snake(name), ", ".join(n for _, n in plist))
        if ret == "void":
            L.append("fn %s(%s) { %s; }" % (_snake(name), sig, call))
        else:
            L.append("fn %s(%s) -> %s { return %s; }" % (_snake(name), sig, rust[ret], call))
    for i, nm in enumerate(["hit_x", "hit_y", "hit_nx", "hit_ny", "hit_impulse"]):
        L.append("fn %s() -> f32 { return p2d_hit[%d]; }" % (nm, i))
    return "\n".join(L) + "\n"


_RUST_LOWER = """import sys
sys.path.insert(0, %r)
from shivyc import crust
path = sys.argv[1]
try:
    code = crust.translate(open(path, encoding="utf-8").read(), path=path)
except crust.CrustError as e:
    print("shivyc: error: crust: " + e.message)
    sys.exit(1)
open(sys.argv[2], "w", encoding="utf-8").write(code)
"""


def build_rust(s, src_path, native_dir, work, cc, api, ids=None):
    """Lowers one Rust script with Crust (shivyc/crust.py) and compiles the C: returns the object file."""
    snake = lambda cb: script_langs.spelling("rust", cb)
    tail = rust_prelude(api, ids) + c_glue(s, lambda cb, inst, args: "%s_%s(&%s%s)" % (s["name"], snake(cb), inst, "".join(", " + a for a in args)))
    path = _copy_with(src_path, native_dir, tail)
    c_path = path[:-len(".rs")] + ".c"
    code, out = _run([sys.executable, "-c", _RUST_LOWER % crust_home(), path, c_path])
    if code != 0 or not os.path.exists(c_path):
        raise Failed(out.strip() or "crust failed")
    return _compile(s, c_path, work, cc)


# ---- RPython

def rpython_prelude(api, ids=None):
    """The engine's calls for an RPython script (snake_case: set_pos, node_x ...): Crust's ctypes subset names each p2d_* function (py2c turns the lookups into extern prototypes
    and direct calls), and wrappers with types give the script plain C ints and floats. Appended to the script."""
    ct = {"int": "ctypes.c_int", "float": "ctypes.c_float"}
    py = {"int": "int", "float": "float", "void": None}
    L = ["", "", "# ---- the engine (tools/script_native.py)", "import rpy_ctypes as ctypes", "_p2d = ctypes.CDLL(\"libstride2d.so\")"]
    L += ["%s = %d" % (id_name(n), i) for n, i in sorted((ids or {}).items(), key=lambda kv: kv[1])]
    calls = [(r, n, p) for r, n, p in api if n not in HOST_ONLY]
    for ret, name, plist in calls:
        f = "_p2d.p2d_%s" % _snake(name)
        if ret != "void":
            L.append("%s.restype = %s" % (f, ct[ret]))
        L.append("%s.argtypes = [%s]" % (f, ", ".join(ct[t] for t, _ in plist)))
    L += ["_p2d.p2dn_hit.restype = ctypes.c_float", "_p2d.p2dn_hit.argtypes = [ctypes.c_int]", ""]
    for ret, name, plist in calls:
        sig = ", ".join("%s: %s" % (n, py[t]) for t, n in plist)
        call = "_p2d.p2d_%s(%s)" % (_snake(name), ", ".join(n for _, n in plist))
        if ret == "void":
            L += ["def %s(%s):" % (_snake(name), sig), "    %s" % call, ""]
        else:
            L += ["def %s(%s) -> %s:" % (_snake(name), sig, py[ret]), "    return %s" % call, ""]
    for i, nm in enumerate(["hit_x", "hit_y", "hit_nx", "hit_ny", "hit_impulse"]):
        L += ["def %s() -> float:" % nm, "    return _p2d.p2dn_hit(%d)" % i, ""]
    return "\n".join(L)


_MARKER_LINES = re.compile(r"^([ \t]*)(@script\b.*|from[ \t]+stride2d[ \t]+import\b.*|import[ \t]+stride2d\b.*)$", re.M)
_runtimes = {}


def _runtime_object(rt_dir, native_dir, work, cc):
    """shivyc_rt.c (py2c's runtime) compiled once per build: the object, the first time it is asked for, else None (it is linked once)."""
    if native_dir in _runtimes and _runtimes[native_dir][0] == work:
        return None
    c_path = os.path.join(rt_dir, "shivyc_rt.c")
    obj = os.path.join(native_dir, "shivyc_rt.o")
    code, out = _run([cc, "-c", "-fPIC", "-O2", "-ffp-contract=off", "-w", "-I", rt_dir, "-o", obj, c_path])
    if code != 0:
        raise Failed(out.strip())
    _runtimes[native_dir] = (work, obj)
    return obj


def build_rpython(s, src_path, native_dir, work, cc, api, ids=None):
    """Lowers one RPython script with py2c (tools/py2c.py) and compiles the C: returns the objects to link (the first script's include the runtime). The marker's decorator and
    import are commented out in the copy (a decorator makes a class a value, and then py2c gives it a header and a vtable instead of a plain struct); the lines stay where they were."""
    n = s["name"]
    rt_dir = os.path.join(native_dir, n + "_rpy")
    with open(src_path, encoding="utf-8") as f:
        text = f.read()
    text = _MARKER_LINES.sub(lambda m: m.group(1) + "# " + m.group(2), text)
    path = os.path.join(native_dir, os.path.basename(src_path))
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text.rstrip("\n") + "\n" + rpython_prelude(api, ids))
    code, out = _run([sys.executable, os.path.join(crust_home(), "tools", "py2c.py"), "--out", rt_dir, path])
    c_path = os.path.join(rt_dir, os.path.splitext(os.path.basename(path))[0] + ".c")
    if code != 0 or not os.path.exists(c_path) or "SYNTAX ERROR" in out or "Transpiled 0/" in out:
        raise Failed(out.strip() or "py2c failed")
    glue = c_glue(s, lambda cb, inst, args: "%s_%s(&%s%s)" % (n, script_langs.spelling("rpython", cb), inst, "".join(", " + a for a in args)), init="%s___init__" % n)
    glue = ("\nstatic float p2d_hit[5];\nfloat p2dn_hit(int i) { return p2d_hit[i]; }\n") + glue
    with open(c_path, "a", encoding="utf-8", newline="\n") as f:
        f.write(glue)
    objs = [_compile(s, c_path, work, cc, ["-I", rt_dir])]
    rt = _runtime_object(rt_dir, native_dir, work, cc)
    return objs + ([rt] if rt else [])


BUILDERS = {"cpp": build_cpp, "rust": build_rust, "rpython": build_rpython}


def built(language):
    return language in BUILDERS or language == "csharp"
